/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for Approach complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Approach">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DescriptiveName" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ApproachNumber" minOccurs="0"/>
 *         &lt;element name="drivingLanes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32" minOccurs="0">
 *                   &lt;element name="VehicleReferenceLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleReferenceLane"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="computedLanes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32" minOccurs="0">
 *                   &lt;element name="VehicleComputedLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleComputedLane"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trainsAndBuses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32" minOccurs="0">
 *                   &lt;element name="SpecialLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpecialLane"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="barriers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32" minOccurs="0">
 *                   &lt;element name="BarrierLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BarrierLane"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="crosswalks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32" minOccurs="0">
 *                   &lt;element name="CrosswalkLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}CrosswalkLane"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Approach", propOrder = { "name", "id", "drivingLanes", "computedLanes", "trainsAndBuses", "barriers", "crosswalks", "any" })
public class Approach implements Serializable {

    protected String name;

    protected Short id;

    protected Approach.DrivingLanes drivingLanes;

    protected Approach.ComputedLanes computedLanes;

    protected Approach.TrainsAndBuses trainsAndBuses;

    protected Approach.Barriers barriers;

    protected Approach.Crosswalks crosswalks;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setId(Short value) {
        this.id = value;
    }

    /**
     * Gets the value of the drivingLanes property.
     * 
     * @return possible object is {@link Approach.DrivingLanes }
     */
    public Approach.DrivingLanes getDrivingLanes() {
        return drivingLanes;
    }

    /**
     * Sets the value of the drivingLanes property.
     * 
     * @param value allowed object is {@link Approach.DrivingLanes }
     */
    public void setDrivingLanes(Approach.DrivingLanes value) {
        this.drivingLanes = value;
    }

    /**
     * Gets the value of the computedLanes property.
     * 
     * @return possible object is {@link Approach.ComputedLanes }
     */
    public Approach.ComputedLanes getComputedLanes() {
        return computedLanes;
    }

    /**
     * Sets the value of the computedLanes property.
     * 
     * @param value allowed object is {@link Approach.ComputedLanes }
     */
    public void setComputedLanes(Approach.ComputedLanes value) {
        this.computedLanes = value;
    }

    /**
     * Gets the value of the trainsAndBuses property.
     * 
     * @return possible object is {@link Approach.TrainsAndBuses }
     */
    public Approach.TrainsAndBuses getTrainsAndBuses() {
        return trainsAndBuses;
    }

    /**
     * Sets the value of the trainsAndBuses property.
     * 
     * @param value allowed object is {@link Approach.TrainsAndBuses }
     */
    public void setTrainsAndBuses(Approach.TrainsAndBuses value) {
        this.trainsAndBuses = value;
    }

    /**
     * Gets the value of the barriers property.
     * 
     * @return possible object is {@link Approach.Barriers }
     */
    public Approach.Barriers getBarriers() {
        return barriers;
    }

    /**
     * Sets the value of the barriers property.
     * 
     * @param value allowed object is {@link Approach.Barriers }
     */
    public void setBarriers(Approach.Barriers value) {
        this.barriers = value;
    }

    /**
     * Gets the value of the crosswalks property.
     * 
     * @return possible object is {@link Approach.Crosswalks }
     */
    public Approach.Crosswalks getCrosswalks() {
        return crosswalks;
    }

    /**
     * Sets the value of the crosswalks property.
     * 
     * @param value allowed object is {@link Approach.Crosswalks }
     */
    public void setCrosswalks(Approach.Crosswalks value) {
        this.crosswalks = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32" minOccurs="0">
     *         &lt;element name="BarrierLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BarrierLane"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "barrierLane" })
    public static class Barriers implements Serializable {

        @XmlElement(name = "BarrierLane")
        protected List<BarrierLane> barrierLane;

        /**
         * Gets the value of the barrierLane property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the barrierLane property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getBarrierLane().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link BarrierLane }
         */
        public List<BarrierLane> getBarrierLane() {
            if (barrierLane == null) {
                barrierLane = new ArrayList<BarrierLane>();
            }
            return this.barrierLane;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32" minOccurs="0">
     *         &lt;element name="VehicleComputedLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleComputedLane"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "vehicleComputedLane" })
    public static class ComputedLanes implements Serializable {

        @XmlElement(name = "VehicleComputedLane")
        protected List<VehicleComputedLane> vehicleComputedLane;

        /**
         * Gets the value of the vehicleComputedLane property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the vehicleComputedLane property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getVehicleComputedLane().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link VehicleComputedLane }
         */
        public List<VehicleComputedLane> getVehicleComputedLane() {
            if (vehicleComputedLane == null) {
                vehicleComputedLane = new ArrayList<VehicleComputedLane>();
            }
            return this.vehicleComputedLane;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32" minOccurs="0">
     *         &lt;element name="CrosswalkLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}CrosswalkLane"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "crosswalkLane" })
    public static class Crosswalks implements Serializable {

        @XmlElement(name = "CrosswalkLane")
        protected List<CrosswalkLane> crosswalkLane;

        /**
         * Gets the value of the crosswalkLane property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the crosswalkLane property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getCrosswalkLane().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link CrosswalkLane }
         */
        public List<CrosswalkLane> getCrosswalkLane() {
            if (crosswalkLane == null) {
                crosswalkLane = new ArrayList<CrosswalkLane>();
            }
            return this.crosswalkLane;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32" minOccurs="0">
     *         &lt;element name="VehicleReferenceLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleReferenceLane"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "vehicleReferenceLane" })
    public static class DrivingLanes implements Serializable {

        @XmlElement(name = "VehicleReferenceLane")
        protected List<VehicleReferenceLane> vehicleReferenceLane;

        /**
         * Gets the value of the vehicleReferenceLane property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the vehicleReferenceLane property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getVehicleReferenceLane().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link VehicleReferenceLane }
         */
        public List<VehicleReferenceLane> getVehicleReferenceLane() {
            if (vehicleReferenceLane == null) {
                vehicleReferenceLane = new ArrayList<VehicleReferenceLane>();
            }
            return this.vehicleReferenceLane;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32" minOccurs="0">
     *         &lt;element name="SpecialLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpecialLane"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "specialLane" })
    public static class TrainsAndBuses implements Serializable {

        @XmlElement(name = "SpecialLane")
        protected List<SpecialLane> specialLane;

        /**
         * Gets the value of the specialLane property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the specialLane property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSpecialLane().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link SpecialLane }
         */
        public List<SpecialLane> getSpecialLane() {
            if (specialLane == null) {
                specialLane = new ArrayList<SpecialLane>();
            }
            return this.specialLane;
        }

    }

}
