/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.etexascode.nonstd.Message;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for BasicSafetyMessage complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicSafetyMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="blob1" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BSMblob"/>
 *         &lt;element name="safetyExt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleSafetyExtension" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleStatus" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "BasicSafetyMessage", propOrder = { "msgID", "blob1", "safetyExt", "status", "any" })
public class BasicSafetyMessage extends Message implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] blob1;

    protected VehicleSafetyExtension safetyExt;

    protected VehicleStatus status;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the blob1 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getBlob1() {
        return blob1.clone();
    }

    /**
     * Sets the value of the blob1 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBlob1(byte[] value) {
        this.blob1 = ((byte[])value.clone());
    }

    /**
     * Gets the value of the safetyExt property.
     * 
     * @return possible object is {@link VehicleSafetyExtension }
     */
    public VehicleSafetyExtension getSafetyExt() {
        return safetyExt;
    }

    /**
     * Sets the value of the safetyExt property.
     * 
     * @param value allowed object is {@link VehicleSafetyExtension }
     */
    public void setSafetyExt(VehicleSafetyExtension value) {
        this.safetyExt = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link VehicleStatus }
     */
    public VehicleStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link VehicleStatus }
     */
    public void setStatus(VehicleStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }
}
