/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.etexascode.nonstd.Message;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for BasicSafetyMessageVerbose complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicSafetyMessageVerbose">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="msgCnt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}MsgCount"/>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TemporaryID"/>
 *         &lt;element name="secMark" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSecond"/>
 *         &lt;element name="lat" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Latitude"/>
 *         &lt;element name="long" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Longitude"/>
 *         &lt;element name="elev" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Elevation"/>
 *         &lt;element name="accuracy" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PositionalAccuracy"/>
 *         &lt;element name="speed" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TransmissionAndSpeed"/>
 *         &lt;element name="heading" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Heading"/>
 *         &lt;element name="angle" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngle"/>
 *         &lt;element name="accelSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelerationSet4Way"/>
 *         &lt;element name="brakes" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BrakeSystemStatus"/>
 *         &lt;element name="size" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleSize"/>
 *         &lt;element name="safetyExt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleSafetyExtension" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleStatus" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
@XmlType(name = "BasicSafetyMessageVerbose", propOrder = { "msgID", "msgCnt", "id", "secMark", "lat", "_long", "elev", "accuracy", "speed", "heading", "angle", "accelSet", "brakes", "size",
        "safetyExt", "status", "any" })
public class BasicSafetyMessageVerbose extends Message implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    protected short msgCnt;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] id;

    protected int secMark;

    protected int lat;

    @XmlElement(name = "long")
    protected int _long;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] elev;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] accuracy;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] speed;

    protected int heading;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] angle;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] accelSet;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] brakes;

    @XmlElement(required = true)
    protected VehicleSize size;

    protected VehicleSafetyExtension safetyExt;

    protected VehicleStatus status;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgCnt property.
     */
    public short getMsgCnt() {
        return msgCnt;
    }

    /**
     * Sets the value of the msgCnt property.
     */
    public void setMsgCnt(short value) {
        this.msgCnt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getId() {
        return id.clone();
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(byte[] value) {
        this.id = ((byte[])value.clone());
    }

    /**
     * Gets the value of the secMark property.
     */
    public int getSecMark() {
        return secMark;
    }

    /**
     * Sets the value of the secMark property.
     */
    public void setSecMark(int value) {
        this.secMark = value;
    }

    /**
     * Gets the value of the lat property.
     */
    public int getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     */
    public void setLat(int value) {
        this.lat = value;
    }

    /**
     * Gets the value of the long property.
     */
    public int getLong() {
        return _long;
    }

    /**
     * Sets the value of the long property.
     */
    public void setLong(int value) {
        this._long = value;
    }

    /**
     * Gets the value of the elev property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getElev() {
        return elev.clone();
    }

    /**
     * Sets the value of the elev property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setElev(byte[] value) {
        this.elev = ((byte[])value.clone());
    }

    /**
     * Gets the value of the accuracy property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getAccuracy() {
        return accuracy.clone();
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAccuracy(byte[] value) {
        this.accuracy = ((byte[])value.clone());
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getSpeed() {
        return speed.clone();
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpeed(byte[] value) {
        this.speed = ((byte[])value.clone());
    }

    /**
     * Gets the value of the heading property.
     */
    public int getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     */
    public void setHeading(int value) {
        this.heading = value;
    }

    /**
     * Gets the value of the angle property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getAngle() {
        return angle.clone();
    }

    /**
     * Sets the value of the angle property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAngle(byte[] value) {
        this.angle = ((byte[])value.clone());
    }

    /**
     * Gets the value of the accelSet property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getAccelSet() {
        return accelSet.clone();
    }

    /**
     * Sets the value of the accelSet property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setAccelSet(byte[] value) {
        this.accelSet = ((byte[])value.clone());
    }

    /**
     * Gets the value of the brakes property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getBrakes() {
        return brakes.clone();
    }

    /**
     * Sets the value of the brakes property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBrakes(byte[] value) {
        this.brakes = ((byte[])value.clone());
    }

    /**
     * Gets the value of the size property.
     * 
     * @return possible object is {@link VehicleSize }
     */
    public VehicleSize getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value allowed object is {@link VehicleSize }
     */
    public void setSize(VehicleSize value) {
        this.size = value;
    }

    /**
     * Gets the value of the safetyExt property.
     * 
     * @return possible object is {@link VehicleSafetyExtension }
     */
    public VehicleSafetyExtension getSafetyExt() {
        return safetyExt;
    }

    /**
     * Sets the value of the safetyExt property.
     * 
     * @param value allowed object is {@link VehicleSafetyExtension }
     */
    public void setSafetyExt(VehicleSafetyExtension value) {
        this.safetyExt = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link VehicleStatus }
     */
    public VehicleStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link VehicleStatus }
     */
    public void setStatus(VehicleStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
