/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Circle complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Circle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="center" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Position3D"/>
 *         &lt;element name="raduis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="radiusSteps">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *                         &lt;minInclusive value="0"/>
 *                         &lt;maxInclusive value="32767"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="miles">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="2000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="km">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="5000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Circle", propOrder = { "center", "raduis" })
public class Circle implements Serializable {

    @XmlElement(required = true)
    protected Position3D center;

    @XmlElement(required = true)
    protected Circle.Raduis raduis;

    /**
     * Gets the value of the center property.
     * 
     * @return possible object is {@link Position3D }
     */
    public Position3D getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     * 
     * @param value allowed object is {@link Position3D }
     */
    public void setCenter(Position3D value) {
        this.center = value;
    }

    /**
     * Gets the value of the raduis property.
     * 
     * @return possible object is {@link Circle.Raduis }
     */
    public Circle.Raduis getRaduis() {
        return raduis;
    }

    /**
     * Sets the value of the raduis property.
     * 
     * @param value allowed object is {@link Circle.Raduis }
     */
    public void setRaduis(Circle.Raduis value) {
        this.raduis = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="radiusSteps">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
     *               &lt;minInclusive value="0"/>
     *               &lt;maxInclusive value="32767"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="miles">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="2000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="km">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="5000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "radiusSteps", "miles", "km" })
    public static class Raduis implements Serializable {

        protected Integer radiusSteps;

        protected Integer miles;

        protected Integer km;

        /**
         * Gets the value of the radiusSteps property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getRadiusSteps() {
            return radiusSteps;
        }

        /**
         * Sets the value of the radiusSteps property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setRadiusSteps(Integer value) {
            this.radiusSteps = value;
        }

        /**
         * Gets the value of the miles property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getMiles() {
            return miles;
        }

        /**
         * Sets the value of the miles property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setMiles(Integer value) {
            this.miles = value;
        }

        /**
         * Gets the value of the km property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getKm() {
            return km;
        }

        /**
         * Sets the value of the km property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setKm(Integer value) {
            this.km = value;
        }

    }

}
