/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for ConfidenceSet complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfidenceSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accelConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelSteerYawRateConfidence" minOccurs="0"/>
 *         &lt;element name="speedConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpeedandHeadingandThrottleConfidence" minOccurs="0"/>
 *         &lt;element name="timeConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TimeConfidence" minOccurs="0"/>
 *         &lt;element name="posConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PositionConfidenceSet" minOccurs="0"/>
 *         &lt;element name="steerConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngleConfidence" minOccurs="0"/>
 *         &lt;element name="throttleConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ThrottleConfidence" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfidenceSet", propOrder = { "accelConfidence", "speedConfidence", "timeConfidence", "posConfidence", "steerConfidence", "throttleConfidence", "any" })
public class ConfidenceSet implements Serializable {

    protected AccelSteerYawRateConfidence accelConfidence;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] speedConfidence;

    protected TimeConfidence timeConfidence;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] posConfidence;

    protected SteeringWheelAngleConfidence steerConfidence;

    protected ThrottleConfidence throttleConfidence;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the accelConfidence property.
     * 
     * @return possible object is {@link AccelSteerYawRateConfidence }
     */
    public AccelSteerYawRateConfidence getAccelConfidence() {
        return accelConfidence;
    }

    /**
     * Sets the value of the accelConfidence property.
     * 
     * @param value allowed object is {@link AccelSteerYawRateConfidence }
     */
    public void setAccelConfidence(AccelSteerYawRateConfidence value) {
        this.accelConfidence = value;
    }

    /**
     * Gets the value of the speedConfidence property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getSpeedConfidence() {
        return speedConfidence.clone();
    }

    /**
     * Sets the value of the speedConfidence property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpeedConfidence(byte[] value) {
        this.speedConfidence = ((byte[])value.clone());
    }

    /**
     * Gets the value of the timeConfidence property.
     * 
     * @return possible object is {@link TimeConfidence }
     */
    public TimeConfidence getTimeConfidence() {
        return timeConfidence;
    }

    /**
     * Sets the value of the timeConfidence property.
     * 
     * @param value allowed object is {@link TimeConfidence }
     */
    public void setTimeConfidence(TimeConfidence value) {
        this.timeConfidence = value;
    }

    /**
     * Gets the value of the posConfidence property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getPosConfidence() {
        return posConfidence.clone();
    }

    /**
     * Sets the value of the posConfidence property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPosConfidence(byte[] value) {
        this.posConfidence = ((byte[])value.clone());
    }

    /**
     * Gets the value of the steerConfidence property.
     * 
     * @return possible object is {@link SteeringWheelAngleConfidence }
     */
    public SteeringWheelAngleConfidence getSteerConfidence() {
        return steerConfidence;
    }

    /**
     * Sets the value of the steerConfidence property.
     * 
     * @param value allowed object is {@link SteeringWheelAngleConfidence }
     */
    public void setSteerConfidence(SteeringWheelAngleConfidence value) {
        this.steerConfidence = value;
    }

    /**
     * Gets the value of the throttleConfidence property.
     * 
     * @return possible object is {@link ThrottleConfidence }
     */
    public ThrottleConfidence getThrottleConfidence() {
        return throttleConfidence;
    }

    /**
     * Sets the value of the throttleConfidence property.
     * 
     * @param value allowed object is {@link ThrottleConfidence }
     */
    public void setThrottleConfidence(ThrottleConfidence value) {
        this.throttleConfidence = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
