/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ElevationConfidence.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="ElevationConfidence">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="unavailable"/>
 *     &lt;enumeration value="elev-500-00"/>
 *     &lt;enumeration value="elev-200-00"/>
 *     &lt;enumeration value="elev-100-00"/>
 *     &lt;enumeration value="elev-050-00"/>
 *     &lt;enumeration value="elev-020-00"/>
 *     &lt;enumeration value="elev-010-00"/>
 *     &lt;enumeration value="elev-005-00"/>
 *     &lt;enumeration value="elev-002-00"/>
 *     &lt;enumeration value="elev-001-00"/>
 *     &lt;enumeration value="elev-000-50"/>
 *     &lt;enumeration value="elev-000-20"/>
 *     &lt;enumeration value="elev-000-10"/>
 *     &lt;enumeration value="elev-000-05"/>
 *     &lt;enumeration value="elev-000-02"/>
 *     &lt;enumeration value="elev-000-01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "ElevationConfidence")
@XmlEnum
public enum ElevationConfidence {

    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable"),
    @XmlEnumValue("elev-500-00")
    ELEV_500_00("elev-500-00"),
    @XmlEnumValue("elev-200-00")
    ELEV_200_00("elev-200-00"),
    @XmlEnumValue("elev-100-00")
    ELEV_100_00("elev-100-00"),
    @XmlEnumValue("elev-050-00")
    ELEV_050_00("elev-050-00"),
    @XmlEnumValue("elev-020-00")
    ELEV_020_00("elev-020-00"),
    @XmlEnumValue("elev-010-00")
    ELEV_010_00("elev-010-00"),
    @XmlEnumValue("elev-005-00")
    ELEV_005_00("elev-005-00"),
    @XmlEnumValue("elev-002-00")
    ELEV_002_00("elev-002-00"),
    @XmlEnumValue("elev-001-00")
    ELEV_001_00("elev-001-00"),
    @XmlEnumValue("elev-000-50")
    ELEV_000_50("elev-000-50"),
    @XmlEnumValue("elev-000-20")
    ELEV_000_20("elev-000-20"),
    @XmlEnumValue("elev-000-10")
    ELEV_000_10("elev-000-10"),
    @XmlEnumValue("elev-000-05")
    ELEV_000_05("elev-000-05"),
    @XmlEnumValue("elev-000-02")
    ELEV_000_02("elev-000-02"),
    @XmlEnumValue("elev-000-01")
    ELEV_000_01("elev-000-01");

    private final String value;

    ElevationConfidence(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ElevationConfidence fromValue(String v) {
        for (ElevationConfidence c : ElevationConfidence.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
