/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for EXTERNAL complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXTERNAL">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="direct-reference" type="{http://www.obj-sys.com/v1.0/XMLSchema}ObjectIdentifier" minOccurs="0"/>
 *         &lt;element name="indirect-reference" type="{http://www.obj-sys.com/v1.0/XMLSchema}ObjectIdentifier" minOccurs="0"/>
 *         &lt;element name="data-value-descriptor" type="{http://www.obj-sys.com/v1.0/XMLSchema}ObjectDescriptor" minOccurs="0"/>
 *         &lt;element name="encoding">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="single-ASN1-type" type="{http://www.obj-sys.com/v1.0/XMLSchema}ObjectIdentifier"/>
 *                   &lt;element name="octet-aligned" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
 *                   &lt;element name="arbitrary" type="{http://www.obj-sys.com/v1.0/XMLSchema}BitString"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXTERNAL", namespace = "http://www.obj-sys.com/v1.0/XMLSchema", propOrder = { "directReference", "indirectReference", "dataValueDescriptor", "encoding" })
public class EXTERNAL implements Serializable {

    @XmlElement(name = "direct-reference", namespace = "")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String directReference;

    @XmlElement(name = "indirect-reference", namespace = "")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String indirectReference;

    @XmlElement(name = "data-value-descriptor", namespace = "")
    protected String dataValueDescriptor;

    @XmlElement(namespace = "", required = true)
    protected EXTERNAL.Encoding encoding;

    /**
     * Gets the value of the directReference property.
     * 
     * @return possible object is {@link String }
     */
    public String getDirectReference() {
        return directReference;
    }

    /**
     * Sets the value of the directReference property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDirectReference(String value) {
        this.directReference = value;
    }

    /**
     * Gets the value of the indirectReference property.
     * 
     * @return possible object is {@link String }
     */
    public String getIndirectReference() {
        return indirectReference;
    }

    /**
     * Sets the value of the indirectReference property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setIndirectReference(String value) {
        this.indirectReference = value;
    }

    /**
     * Gets the value of the dataValueDescriptor property.
     * 
     * @return possible object is {@link String }
     */
    public String getDataValueDescriptor() {
        return dataValueDescriptor;
    }

    /**
     * Sets the value of the dataValueDescriptor property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDataValueDescriptor(String value) {
        this.dataValueDescriptor = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return possible object is {@link EXTERNAL.Encoding }
     */
    public EXTERNAL.Encoding getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value allowed object is {@link EXTERNAL.Encoding }
     */
    public void setEncoding(EXTERNAL.Encoding value) {
        this.encoding = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="single-ASN1-type" type="{http://www.obj-sys.com/v1.0/XMLSchema}ObjectIdentifier"/>
     *         &lt;element name="octet-aligned" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/>
     *         &lt;element name="arbitrary" type="{http://www.obj-sys.com/v1.0/XMLSchema}BitString"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "singleASN1Type", "octetAligned", "arbitrary" })
    public static class Encoding implements Serializable {

        @XmlElement(name = "single-ASN1-type", namespace = "")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String singleASN1Type;

        @XmlElement(name = "octet-aligned", namespace = "", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] octetAligned;

        @XmlElement(namespace = "")
        protected String arbitrary;

        /**
         * Gets the value of the singleASN1Type property.
         * 
         * @return possible object is {@link String }
         */
        public String getSingleASN1Type() {
            return singleASN1Type;
        }

        /**
         * Sets the value of the singleASN1Type property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setSingleASN1Type(String value) {
            this.singleASN1Type = value;
        }

        /**
         * Gets the value of the octetAligned property.
         * 
         * @return possible object is {@link String }
         */
        public byte[] getOctetAligned() {
            return octetAligned.clone();
        }

        /**
         * Sets the value of the octetAligned property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setOctetAligned(byte[] value) {
            this.octetAligned = ((byte[])value.clone());
        }

        /**
         * Gets the value of the arbitrary property.
         * 
         * @return possible object is {@link String }
         */
        public String getArbitrary() {
            return arbitrary;
        }

        /**
         * Sets the value of the arbitrary property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setArbitrary(String value) {
            this.arbitrary = value;
        }

    }

}
