/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for Intersection complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Intersection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DescriptiveName" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionID"/>
 *         &lt;element name="refPoint" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Position3D" minOccurs="0"/>
 *         &lt;element name="refInterNum" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionID" minOccurs="0"/>
 *         &lt;element name="orientation" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Heading" minOccurs="0"/>
 *         &lt;element name="laneWidth" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneWidth" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionStatusObject" minOccurs="0"/>
 *         &lt;element name="approaches">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32">
 *                   &lt;element name="ApproachObject" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ApproachObject"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preemptZones" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32">
 *                   &lt;element name="SignalControlZone" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalControlZone"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="priorityZones" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32">
 *                   &lt;element name="SignalControlZone" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalControlZone"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Intersection", propOrder = { "name", "id", "refPoint", "refInterNum", "orientation", "laneWidth", "type", "approaches", "preemptZones", "priorityZones", "any" })
public class Intersection implements Serializable {

    /** Serial ID. */
    private static final long serialVersionUID = -8590100084756666084L;

    protected String name;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] id;

    protected Position3D refPoint;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] refInterNum;

    protected Integer orientation;

    protected Integer laneWidth;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] type;

    @XmlElement(required = true)
    protected Intersection.Approaches approaches;

    protected Intersection.PreemptZones preemptZones;

    protected Intersection.PriorityZones priorityZones;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getId() {
        return id.clone();
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(byte[] value) {
        this.id = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the refPoint property.
     * 
     * @return possible object is {@link Position3D }
     */
    public Position3D getRefPoint() {
        return refPoint;
    }

    /**
     * Sets the value of the refPoint property.
     * 
     * @param value allowed object is {@link Position3D }
     */
    public void setRefPoint(Position3D value) {
        this.refPoint = value;
    }

    /**
     * Gets the value of the refInterNum property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getRefInterNum() {
        if (refInterNum == null) {
            return null;
        }
        else {
            return refInterNum.clone();
        }

    }

    /**
     * Sets the value of the refInterNum property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRefInterNum(byte[] value) {
        this.refInterNum = ((byte[])value.clone());
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setOrientation(Integer value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the laneWidth property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getLaneWidth() {
        return laneWidth;
    }

    /**
     * Sets the value of the laneWidth property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setLaneWidth(Integer value) {
        this.laneWidth = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getType() {
        return type == null ? null : type.clone();
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setType(byte[] value) {
        this.type = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the approaches property.
     * 
     * @return possible object is {@link Intersection.Approaches }
     */
    public Intersection.Approaches getApproaches() {
        return approaches;
    }

    /**
     * Sets the value of the approaches property.
     * 
     * @param value allowed object is {@link Intersection.Approaches }
     */
    public void setApproaches(Intersection.Approaches value) {
        this.approaches = value;
    }

    /**
     * Gets the value of the preemptZones property.
     * 
     * @return possible object is {@link Intersection.PreemptZones }
     */
    public Intersection.PreemptZones getPreemptZones() {
        return preemptZones;
    }

    /**
     * Sets the value of the preemptZones property.
     * 
     * @param value allowed object is {@link Intersection.PreemptZones }
     */
    public void setPreemptZones(Intersection.PreemptZones value) {
        this.preemptZones = value;
    }

    /**
     * Gets the value of the priorityZones property.
     * 
     * @return possible object is {@link Intersection.PriorityZones }
     */
    public Intersection.PriorityZones getPriorityZones() {
        return priorityZones;
    }

    /**
     * Sets the value of the priorityZones property.
     * 
     * @param value allowed object is {@link Intersection.PriorityZones }
     */
    public void setPriorityZones(Intersection.PriorityZones value) {
        this.priorityZones = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32">
     *         &lt;element name="ApproachObject" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ApproachObject"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "approachObject" })
    public static class Approaches implements Serializable {

        /** Serial ID. */
        private static final long serialVersionUID = -6169281673833183629L;

        @XmlElement(name = "ApproachObject", required = true)
        protected List<ApproachObject> approachObject;

        /**
         * Gets the value of the approachObject property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the approachObject property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getApproachObject().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link ApproachObject }
         */
        public List<ApproachObject> getApproachObject() {
            if (approachObject == null) {
                approachObject = new ArrayList<ApproachObject>();
            }
            return this.approachObject;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32">
     *         &lt;element name="SignalControlZone" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalControlZone"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "signalControlZone" })
    public static class PreemptZones implements Serializable {

        /** Serial ID. */
        private static final long serialVersionUID = -7433867162638751187L;

        @XmlElement(name = "SignalControlZone", required = true)
        protected List<SignalControlZone> signalControlZone;

        /**
         * Gets the value of the signalControlZone property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the signalControlZone property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSignalControlZone().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link SignalControlZone }
         */
        public List<SignalControlZone> getSignalControlZone() {
            if (signalControlZone == null) {
                signalControlZone = new ArrayList<SignalControlZone>();
            }
            return this.signalControlZone;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32">
     *         &lt;element name="SignalControlZone" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalControlZone"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "signalControlZone" })
    public static class PriorityZones implements Serializable {

        /** Serial ID. */
        private static final long serialVersionUID = 8636727502115966682L;

        @XmlElement(name = "SignalControlZone", required = true)
        protected List<SignalControlZone> signalControlZone;

        /**
         * Gets the value of the signalControlZone property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the signalControlZone property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSignalControlZone().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link SignalControlZone }
         */
        public List<SignalControlZone> getSignalControlZone() {
            if (signalControlZone == null) {
                signalControlZone = new ArrayList<SignalControlZone>();
            }
            return this.signalControlZone;
        }

    }

}
