/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for IntersectionCollision complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntersectionCollision">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="msgCnt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}MsgCount"/>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TemporaryID"/>
 *         &lt;element name="secMark" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSecond" minOccurs="0"/>
 *         &lt;element name="path" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PathHistory"/>
 *         &lt;element name="intersetionID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionID"/>
 *         &lt;element name="laneNumber" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneNumber"/>
 *         &lt;element name="eventFlag" type="{http://www.DSRC-Adopted-02-00-36/DSRC}EventFlags"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntersectionCollision", propOrder = { "msgID", "msgCnt", "id", "secMark", "path", "intersetionID", "laneNumber", "eventFlag", "any" })
public class IntersectionCollision implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    protected short msgCnt;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] id;

    protected Integer secMark;

    @XmlElement(required = true)
    protected PathHistory path;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] intersetionID;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] laneNumber;

    protected int eventFlag;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgCnt property.
     */
    public short getMsgCnt() {
        return msgCnt;
    }

    /**
     * Sets the value of the msgCnt property.
     */
    public void setMsgCnt(short value) {
        this.msgCnt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getId() {
        return id.clone();
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(byte[] value) {
        this.id = ((byte[])value.clone());
    }

    /**
     * Gets the value of the secMark property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getSecMark() {
        return secMark;
    }

    /**
     * Sets the value of the secMark property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setSecMark(Integer value) {
        this.secMark = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return possible object is {@link PathHistory }
     */
    public PathHistory getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value allowed object is {@link PathHistory }
     */
    public void setPath(PathHistory value) {
        this.path = value;
    }

    /**
     * Gets the value of the intersetionID property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getIntersetionID() {
        return intersetionID.clone();
    }

    /**
     * Sets the value of the intersetionID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setIntersetionID(byte[] value) {
        this.intersetionID = ((byte[])value.clone());
    }

    /**
     * Gets the value of the laneNumber property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getLaneNumber() {
        return laneNumber.clone();
    }

    /**
     * Sets the value of the laneNumber property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLaneNumber(byte[] value) {
        this.laneNumber = ((byte[])value.clone());
    }

    /**
     * Gets the value of the eventFlag property.
     */
    public int getEventFlag() {
        return eventFlag;
    }

    /**
     * Sets the value of the eventFlag property.
     */
    public void setEventFlag(int value) {
        this.eventFlag = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
