/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for J1939data complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="J1939data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tires" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="16" minOccurs="0">
 *                   &lt;element name="SEQUENCE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLocation" minOccurs="0"/>
 *                             &lt;element name="pressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressure" minOccurs="0"/>
 *                             &lt;element name="temp" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireTemp" minOccurs="0"/>
 *                             &lt;element name="wheelSensorStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelSensorStatus" minOccurs="0"/>
 *                             &lt;element name="wheelEndElectFault" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelEndElectFault" minOccurs="0"/>
 *                             &lt;element name="leakageRate" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLeakageRate" minOccurs="0"/>
 *                             &lt;element name="detection" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressureThresholdDetection" minOccurs="0"/>
 *                             &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="axle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="16" minOccurs="0">
 *                   &lt;element name="SEQUENCE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleLocation" minOccurs="0"/>
 *                             &lt;element name="weight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleWeight" minOccurs="0"/>
 *                             &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="trailerWeight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TrailerWeight" minOccurs="0"/>
 *         &lt;element name="cargoWeight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}CargoWeight" minOccurs="0"/>
 *         &lt;element name="steeringAxleTemperature" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringAxleTemperature" minOccurs="0"/>
 *         &lt;element name="driveAxleLocation" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DriveAxleLocation" minOccurs="0"/>
 *         &lt;element name="driveAxleLiftAirPressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DriveAxleLiftAirPressure" minOccurs="0"/>
 *         &lt;element name="driveAxleTemperature" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DriveAxleTemperature" minOccurs="0"/>
 *         &lt;element name="driveAxleLubePressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DriveAxleLubePressure" minOccurs="0"/>
 *         &lt;element name="steeringAxleLubePressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringAxleLubePressure" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "J1939data", propOrder = { "tires", "axle", "trailerWeight", "cargoWeight", "steeringAxleTemperature", "driveAxleLocation", "driveAxleLiftAirPressure", "driveAxleTemperature",
        "driveAxleLubePressure", "steeringAxleLubePressure", "any" })
public class J1939Data implements Serializable {

    protected J1939Data.Tires tires;

    protected J1939Data.Axle axle;

    protected Integer trailerWeight;

    protected Integer cargoWeight;

    protected Short steeringAxleTemperature;

    protected Short driveAxleLocation;

    protected Integer driveAxleLiftAirPressure;

    protected Short driveAxleTemperature;

    protected Integer driveAxleLubePressure;

    protected Short steeringAxleLubePressure;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the tires property.
     * 
     * @return possible object is {@link J1939Data.Tires }
     */
    public J1939Data.Tires getTires() {
        return tires;
    }

    /**
     * Sets the value of the tires property.
     * 
     * @param value allowed object is {@link J1939Data.Tires }
     */
    public void setTires(J1939Data.Tires value) {
        this.tires = value;
    }

    /**
     * Gets the value of the axle property.
     * 
     * @return possible object is {@link J1939Data.Axle }
     */
    public J1939Data.Axle getAxle() {
        return axle;
    }

    /**
     * Sets the value of the axle property.
     * 
     * @param value allowed object is {@link J1939Data.Axle }
     */
    public void setAxle(J1939Data.Axle value) {
        this.axle = value;
    }

    /**
     * Gets the value of the trailerWeight property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getTrailerWeight() {
        return trailerWeight;
    }

    /**
     * Sets the value of the trailerWeight property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setTrailerWeight(Integer value) {
        this.trailerWeight = value;
    }

    /**
     * Gets the value of the cargoWeight property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getCargoWeight() {
        return cargoWeight;
    }

    /**
     * Sets the value of the cargoWeight property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setCargoWeight(Integer value) {
        this.cargoWeight = value;
    }

    /**
     * Gets the value of the steeringAxleTemperature property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getSteeringAxleTemperature() {
        return steeringAxleTemperature;
    }

    /**
     * Sets the value of the steeringAxleTemperature property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setSteeringAxleTemperature(Short value) {
        this.steeringAxleTemperature = value;
    }

    /**
     * Gets the value of the driveAxleLocation property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getDriveAxleLocation() {
        return driveAxleLocation;
    }

    /**
     * Sets the value of the driveAxleLocation property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setDriveAxleLocation(Short value) {
        this.driveAxleLocation = value;
    }

    /**
     * Gets the value of the driveAxleLiftAirPressure property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getDriveAxleLiftAirPressure() {
        return driveAxleLiftAirPressure;
    }

    /**
     * Sets the value of the driveAxleLiftAirPressure property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setDriveAxleLiftAirPressure(Integer value) {
        this.driveAxleLiftAirPressure = value;
    }

    /**
     * Gets the value of the driveAxleTemperature property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getDriveAxleTemperature() {
        return driveAxleTemperature;
    }

    /**
     * Sets the value of the driveAxleTemperature property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setDriveAxleTemperature(Short value) {
        this.driveAxleTemperature = value;
    }

    /**
     * Gets the value of the driveAxleLubePressure property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getDriveAxleLubePressure() {
        return driveAxleLubePressure;
    }

    /**
     * Sets the value of the driveAxleLubePressure property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setDriveAxleLubePressure(Integer value) {
        this.driveAxleLubePressure = value;
    }

    /**
     * Gets the value of the steeringAxleLubePressure property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getSteeringAxleLubePressure() {
        return steeringAxleLubePressure;
    }

    /**
     * Sets the value of the steeringAxleLubePressure property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setSteeringAxleLubePressure(Short value) {
        this.steeringAxleLubePressure = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="16" minOccurs="0">
     *         &lt;element name="SEQUENCE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleLocation" minOccurs="0"/>
     *                   &lt;element name="weight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleWeight" minOccurs="0"/>
     *                   &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "sequence" })
    public static class Axle implements Serializable {

        @XmlElement(name = "SEQUENCE")
        protected List<J1939Data.Axle.SEQUENCE> sequence;

        /**
         * Gets the value of the sequence property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the sequence property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSEQUENCE().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link J1939Data.Axle.SEQUENCE }
         */
        public List<J1939Data.Axle.SEQUENCE> getSEQUENCE() {
            if (sequence == null) {
                sequence = new ArrayList<J1939Data.Axle.SEQUENCE>();
            }
            return this.sequence;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleLocation" minOccurs="0"/>
         *         &lt;element name="weight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AxleWeight" minOccurs="0"/>
         *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "location", "weight", "any" })
        public static class SEQUENCE implements Serializable {

            protected Short location;

            protected Integer weight;

            @XmlAnyElement(lax = true)
            protected Object any;

            /**
             * Gets the value of the location property.
             * 
             * @return possible object is {@link Short }
             */
            public Short getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value allowed object is {@link Short }
             */
            public void setLocation(Short value) {
                this.location = value;
            }

            /**
             * Gets the value of the weight property.
             * 
             * @return possible object is {@link Integer }
             */
            public Integer getWeight() {
                return weight;
            }

            /**
             * Sets the value of the weight property.
             * 
             * @param value allowed object is {@link Integer }
             */
            public void setWeight(Integer value) {
                this.weight = value;
            }

            /**
             * Gets the value of the any property.
             * 
             * @return possible object is {@link Element } {@link Object }
             */
            public Object getAny() {
                return any;
            }

            /**
             * Sets the value of the any property.
             * 
             * @param value allowed object is {@link Element } {@link Object }
             */
            public void setAny(Object value) {
                this.any = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="16" minOccurs="0">
     *         &lt;element name="SEQUENCE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLocation" minOccurs="0"/>
     *                   &lt;element name="pressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressure" minOccurs="0"/>
     *                   &lt;element name="temp" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireTemp" minOccurs="0"/>
     *                   &lt;element name="wheelSensorStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelSensorStatus" minOccurs="0"/>
     *                   &lt;element name="wheelEndElectFault" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelEndElectFault" minOccurs="0"/>
     *                   &lt;element name="leakageRate" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLeakageRate" minOccurs="0"/>
     *                   &lt;element name="detection" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressureThresholdDetection" minOccurs="0"/>
     *                   &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "sequence" })
    public static class Tires implements Serializable {

        @XmlElement(name = "SEQUENCE")
        protected List<J1939Data.Tires.SEQUENCE> sequence;

        /**
         * Gets the value of the sequence property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the sequence property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getSEQUENCE().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link J1939Data.Tires.SEQUENCE }
         */
        public List<J1939Data.Tires.SEQUENCE> getSEQUENCE() {
            if (sequence == null) {
                sequence = new ArrayList<J1939Data.Tires.SEQUENCE>();
            }
            return this.sequence;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="location" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLocation" minOccurs="0"/>
         *         &lt;element name="pressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressure" minOccurs="0"/>
         *         &lt;element name="temp" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireTemp" minOccurs="0"/>
         *         &lt;element name="wheelSensorStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelSensorStatus" minOccurs="0"/>
         *         &lt;element name="wheelEndElectFault" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WheelEndElectFault" minOccurs="0"/>
         *         &lt;element name="leakageRate" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TireLeakageRate" minOccurs="0"/>
         *         &lt;element name="detection" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TirePressureThresholdDetection" minOccurs="0"/>
         *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "location", "pressure", "temp", "wheelSensorStatus", "wheelEndElectFault", "leakageRate", "detection", "any" })
        public static class SEQUENCE implements Serializable {

            protected Short location;

            protected Integer pressure;

            protected Integer temp;

            protected WheelSensorStatus wheelSensorStatus;

            @XmlList
            protected List<String> wheelEndElectFault;

            protected Integer leakageRate;

            protected String detection;

            @XmlAnyElement(lax = true)
            protected Object any;

            /**
             * Gets the value of the location property.
             * 
             * @return possible object is {@link Short }
             */
            public Short getLocation() {
                return location;
            }

            /**
             * Sets the value of the location property.
             * 
             * @param value allowed object is {@link Short }
             */
            public void setLocation(Short value) {
                this.location = value;
            }

            /**
             * Gets the value of the pressure property.
             * 
             * @return possible object is {@link Integer }
             */
            public Integer getPressure() {
                return pressure;
            }

            /**
             * Sets the value of the pressure property.
             * 
             * @param value allowed object is {@link Integer }
             */
            public void setPressure(Integer value) {
                this.pressure = value;
            }

            /**
             * Gets the value of the temp property.
             * 
             * @return possible object is {@link Integer }
             */
            public Integer getTemp() {
                return temp;
            }

            /**
             * Sets the value of the temp property.
             * 
             * @param value allowed object is {@link Integer }
             */
            public void setTemp(Integer value) {
                this.temp = value;
            }

            /**
             * Gets the value of the wheelSensorStatus property.
             * 
             * @return possible object is {@link WheelSensorStatus }
             */
            public WheelSensorStatus getWheelSensorStatus() {
                return wheelSensorStatus;
            }

            /**
             * Sets the value of the wheelSensorStatus property.
             * 
             * @param value allowed object is {@link WheelSensorStatus }
             */
            public void setWheelSensorStatus(WheelSensorStatus value) {
                this.wheelSensorStatus = value;
            }

            /**
             * Gets the value of the wheelEndElectFault property.
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore
             * any modification you make to the returned list will be present inside the JAXB
             * object. This is why there is not a <CODE>set</CODE> method for the wheelEndElectFault
             * property.
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getWheelEndElectFault().add(newItem);
             * </pre>
             * <p>
             * Objects of the following type(s) are allowed in the list {@link String }
             */
            public List<String> getWheelEndElectFault() {
                if (wheelEndElectFault == null) {
                    wheelEndElectFault = new ArrayList<String>();
                }
                return this.wheelEndElectFault;
            }

            /**
             * Gets the value of the leakageRate property.
             * 
             * @return possible object is {@link Integer }
             */
            public Integer getLeakageRate() {
                return leakageRate;
            }

            /**
             * Sets the value of the leakageRate property.
             * 
             * @param value allowed object is {@link Integer }
             */
            public void setLeakageRate(Integer value) {
                this.leakageRate = value;
            }

            /**
             * Gets the value of the detection property.
             * 
             * @return possible object is {@link String }
             */
            public String getDetection() {
                return detection;
            }

            /**
             * Sets the value of the detection property.
             * 
             * @param value allowed object is {@link String }
             */
            public void setDetection(String value) {
                this.detection = value;
            }

            /**
             * Gets the value of the any property.
             * 
             * @return possible object is {@link Element } {@link Object }
             */
            public Object getAny() {
                return any;
            }

            /**
             * Sets the value of the any property.
             * 
             * @param value allowed object is {@link Element } {@link Object }
             */
            public void setAny(Object value) {
                this.any = value;
            }

        }

    }

}
