/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Location-quality.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Location-quality">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="loc-qual-bt1m"/>
 *     &lt;enumeration value="loc-qual-bt5m"/>
 *     &lt;enumeration value="loc-qual-bt12m"/>
 *     &lt;enumeration value="loc-qual-bt50m"/>
 *     &lt;enumeration value="loc-qual-bt125m"/>
 *     &lt;enumeration value="loc-qual-bt500m"/>
 *     &lt;enumeration value="loc-qual-bt1250m"/>
 *     &lt;enumeration value="loc-qual-unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "Location-quality")
@XmlEnum
public enum LocationQuality {

    @XmlEnumValue("loc-qual-bt1m")
    LOC_QUAL_BT_1_M("loc-qual-bt1m"),
    @XmlEnumValue("loc-qual-bt5m")
    LOC_QUAL_BT_5_M("loc-qual-bt5m"),
    @XmlEnumValue("loc-qual-bt12m")
    LOC_QUAL_BT_12_M("loc-qual-bt12m"),
    @XmlEnumValue("loc-qual-bt50m")
    LOC_QUAL_BT_50_M("loc-qual-bt50m"),
    @XmlEnumValue("loc-qual-bt125m")
    LOC_QUAL_BT_125_M("loc-qual-bt125m"),
    @XmlEnumValue("loc-qual-bt500m")
    LOC_QUAL_BT_500_M("loc-qual-bt500m"),
    @XmlEnumValue("loc-qual-bt1250m")
    LOC_QUAL_BT_1250_M("loc-qual-bt1250m"),
    @XmlEnumValue("loc-qual-unknown")
    LOC_QUAL_UNKNOWN("loc-qual-unknown");

    private final String value;

    LocationQuality(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LocationQuality fromValue(String v) {
        for (LocationQuality c : LocationQuality.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
