/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for MovementState complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MovementState">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="movementName" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DescriptiveName" minOccurs="0"/>
 *         &lt;element name="laneCnt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneCount" minOccurs="0"/>
 *         &lt;element name="laneSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneSet"/>
 *         &lt;element name="currState" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalLightState" minOccurs="0"/>
 *         &lt;element name="pedState" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PedestrianSignalState" minOccurs="0"/>
 *         &lt;element name="specialState" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpecialSignalState" minOccurs="0"/>
 *         &lt;element name="timeToChange" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TimeMark"/>
 *         &lt;element name="stateConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}StateConfidence" minOccurs="0"/>
 *         &lt;element name="yellState" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalLightState" minOccurs="0"/>
 *         &lt;element name="yellPedState" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PedestrianSignalState" minOccurs="0"/>
 *         &lt;element name="yellTimeToChange" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TimeMark" minOccurs="0"/>
 *         &lt;element name="yellStateConfidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}StateConfidence" minOccurs="0"/>
 *         &lt;element name="vehicleCount" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObjectCount" minOccurs="0"/>
 *         &lt;element name="pedDetect" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PedestrianDetect" minOccurs="0"/>
 *         &lt;element name="pedCount" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObjectCount" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MovementState", propOrder = { "movementName", "laneCnt", "laneSet", "currState", "pedState", "specialState", "timeToChange", "stateConfidence", "yellState", "yellPedState",
        "yellTimeToChange", "yellStateConfidence", "vehicleCount", "pedDetect", "pedCount", "any" })
public class MovementState implements Serializable {

    protected String movementName;

    protected Short laneCnt;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] laneSet;

    protected Long currState;

    protected String pedState;

    protected String specialState;

    protected int timeToChange;

    protected String stateConfidence;

    protected Long yellState;

    protected String yellPedState;

    protected Integer yellTimeToChange;

    protected String yellStateConfidence;

    protected Integer vehicleCount;

    protected String pedDetect;

    protected Integer pedCount;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the movementName property.
     * 
     * @return possible object is {@link String }
     */
    public String getMovementName() {
        return movementName;
    }

    /**
     * Sets the value of the movementName property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMovementName(String value) {
        this.movementName = value;
    }

    /**
     * Gets the value of the laneCnt property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getLaneCnt() {
        return laneCnt;
    }

    /**
     * Sets the value of the laneCnt property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setLaneCnt(Short value) {
        this.laneCnt = value;
    }

    /**
     * Gets the value of the laneSet property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getLaneSet() {
        return laneSet.clone();
    }

    /**
     * Sets the value of the laneSet property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setLaneSet(byte[] value) {
        this.laneSet = ((byte[])value.clone());
    }

    /**
     * Gets the value of the currState property.
     * 
     * @return possible object is {@link Long }
     */
    public Long getCurrState() {
        return currState;
    }

    /**
     * Sets the value of the currState property.
     * 
     * @param value allowed object is {@link Long }
     */
    public void setCurrState(Long value) {
        this.currState = value;
    }

    /**
     * Gets the value of the pedState property.
     * 
     * @return possible object is {@link String }
     */
    public String getPedState() {
        return pedState;
    }

    /**
     * Sets the value of the pedState property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPedState(String value) {
        this.pedState = value;
    }

    /**
     * Gets the value of the specialState property.
     * 
     * @return possible object is {@link String }
     */
    public String getSpecialState() {
        return specialState;
    }

    /**
     * Sets the value of the specialState property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpecialState(String value) {
        this.specialState = value;
    }

    /**
     * Gets the value of the timeToChange property.
     */
    public int getTimeToChange() {
        return timeToChange;
    }

    /**
     * Sets the value of the timeToChange property.
     */
    public void setTimeToChange(int value) {
        this.timeToChange = value;
    }

    /**
     * Gets the value of the stateConfidence property.
     * 
     * @return possible object is {@link String }
     */
    public String getStateConfidence() {
        return stateConfidence;
    }

    /**
     * Sets the value of the stateConfidence property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStateConfidence(String value) {
        this.stateConfidence = value;
    }

    /**
     * Gets the value of the yellState property.
     * 
     * @return possible object is {@link Long }
     */
    public Long getYellState() {
        return yellState;
    }

    /**
     * Sets the value of the yellState property.
     * 
     * @param value allowed object is {@link Long }
     */
    public void setYellState(Long value) {
        this.yellState = value;
    }

    /**
     * Gets the value of the yellPedState property.
     * 
     * @return possible object is {@link String }
     */
    public String getYellPedState() {
        return yellPedState;
    }

    /**
     * Sets the value of the yellPedState property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setYellPedState(String value) {
        this.yellPedState = value;
    }

    /**
     * Gets the value of the yellTimeToChange property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getYellTimeToChange() {
        return yellTimeToChange;
    }

    /**
     * Sets the value of the yellTimeToChange property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setYellTimeToChange(Integer value) {
        this.yellTimeToChange = value;
    }

    /**
     * Gets the value of the yellStateConfidence property.
     * 
     * @return possible object is {@link String }
     */
    public String getYellStateConfidence() {
        return yellStateConfidence;
    }

    /**
     * Sets the value of the yellStateConfidence property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setYellStateConfidence(String value) {
        this.yellStateConfidence = value;
    }

    /**
     * Gets the value of the vehicleCount property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getVehicleCount() {
        return vehicleCount;
    }

    /**
     * Sets the value of the vehicleCount property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setVehicleCount(Integer value) {
        this.vehicleCount = value;
    }

    /**
     * Gets the value of the pedDetect property.
     * 
     * @return possible object is {@link String }
     */
    public String getPedDetect() {
        return pedDetect;
    }

    /**
     * Sets the value of the pedDetect property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPedDetect(String value) {
        this.pedDetect = value;
    }

    /**
     * Gets the value of the pedCount property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getPedCount() {
        return pedCount;
    }

    /**
     * Sets the value of the pedCount property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setPedCount(Integer value) {
        this.pedCount = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
