/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for PathHistoryPointType-01 complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PathHistoryPointType-01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="latOffset">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-131072"/>
 *               &lt;maxInclusive value="131071"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="longOffset">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="-131072"/>
 *               &lt;maxInclusive value="131071"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="elevationOffset" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;minInclusive value="-2048"/>
 *               &lt;maxInclusive value="2047"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="timeOffset" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedShort">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="65535"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="posAccuracy" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PositionalAccuracy" minOccurs="0"/>
 *         &lt;element name="heading" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="speed" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TransmissionAndSpeed" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PathHistoryPointType-01", propOrder = { "latOffset", "longOffset", "elevationOffset", "timeOffset", "posAccuracy", "heading", "speed" })
public class PathHistoryPointType01 implements Serializable {

    protected int latOffset;

    protected int longOffset;

    protected Short elevationOffset;

    protected Integer timeOffset;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] posAccuracy;

    protected Byte heading;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] speed;

    /**
     * Gets the value of the latOffset property.
     */
    public int getLatOffset() {
        return latOffset;
    }

    /**
     * Sets the value of the latOffset property.
     */
    public void setLatOffset(int value) {
        this.latOffset = value;
    }

    /**
     * Gets the value of the longOffset property.
     */
    public int getLongOffset() {
        return longOffset;
    }

    /**
     * Sets the value of the longOffset property.
     */
    public void setLongOffset(int value) {
        this.longOffset = value;
    }

    /**
     * Gets the value of the elevationOffset property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getElevationOffset() {
        return elevationOffset;
    }

    /**
     * Sets the value of the elevationOffset property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setElevationOffset(Short value) {
        this.elevationOffset = value;
    }

    /**
     * Gets the value of the timeOffset property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getTimeOffset() {
        return timeOffset;
    }

    /**
     * Sets the value of the timeOffset property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setTimeOffset(Integer value) {
        this.timeOffset = value;
    }

    /**
     * Gets the value of the posAccuracy property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getPosAccuracy() {
        return posAccuracy.clone();
    }

    /**
     * Sets the value of the posAccuracy property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setPosAccuracy(byte[] value) {
        this.posAccuracy = ((byte[])value.clone());
    }

    /**
     * Gets the value of the heading property.
     * 
     * @return possible object is {@link Byte }
     */
    public Byte getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value allowed object is {@link Byte }
     */
    public void setHeading(Byte value) {
        this.heading = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getSpeed() {
        return speed.clone();
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpeed(byte[] value) {
        this.speed = ((byte[])value.clone());
    }

}
