/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Position3D complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Position3D">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lat" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Latitude"/>
 *         &lt;element name="long" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Longitude"/>
 *         &lt;element name="elevation" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Elevation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position3D", propOrder = { "lat", "_long", "elevation" })
public class Position3D implements Serializable {

    protected int lat;

    @XmlElement(name = "long")
    protected int _long;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] elevation;

    /**
     * Gets the value of the lat property.
     */
    public int getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     */
    public void setLat(int value) {
        this.lat = value;
    }

    /**
     * Gets the value of the long property.
     */
    public int getLong() {
        return _long;
    }

    /**
     * Sets the value of the long property.
     */
    public void setLong(int value) {
        this._long = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getElevation() {
        return elevation == null ? null : elevation.clone();
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setElevation(byte[] value) {
        this.elevation = ((byte[])value.clone());
    }

}
