/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for ProbeDataManagement complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProbeDataManagement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="sample" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Sample"/>
 *         &lt;element name="directions" type="{http://www.DSRC-Adopted-02-00-36/DSRC}HeadingSlice"/>
 *         &lt;element name="term">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="termtime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TermTime"/>
 *                   &lt;element name="termDistance" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TermDistance"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="snapshot">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="snapshotTime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SnapshotTime"/>
 *                   &lt;element name="snapshotDistance" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SnapshotDistance"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="txInterval" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TxTime"/>
 *         &lt;element name="cntTthreshold" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Count"/>
 *         &lt;element name="dataElements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="32">
 *                   &lt;element name="VehicleStatusRequest" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleStatusRequest"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProbeDataManagement", propOrder = { "msgID", "sample", "directions", "term", "snapshot", "txInterval", "cntTthreshold", "dataElements", "any" })
public class ProbeDataManagement implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    @XmlElement(required = true)
    protected Sample sample;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] directions;

    @XmlElement(required = true)
    protected ProbeDataManagement.Term term;

    @XmlElement(required = true)
    protected ProbeDataManagement.Snapshot snapshot;

    protected short txInterval;

    protected short cntTthreshold;

    @XmlElement(required = true)
    protected ProbeDataManagement.DataElements dataElements;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the sample property.
     * 
     * @return possible object is {@link Sample }
     */
    public Sample getSample() {
        return sample;
    }

    /**
     * Sets the value of the sample property.
     * 
     * @param value allowed object is {@link Sample }
     */
    public void setSample(Sample value) {
        this.sample = value;
    }

    /**
     * Gets the value of the directions property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getDirections() {
        return directions.clone();
    }

    /**
     * Sets the value of the directions property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDirections(byte[] value) {
        this.directions = ((byte[])value.clone());
    }

    /**
     * Gets the value of the term property.
     * 
     * @return possible object is {@link ProbeDataManagement.Term }
     */
    public ProbeDataManagement.Term getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value allowed object is {@link ProbeDataManagement.Term }
     */
    public void setTerm(ProbeDataManagement.Term value) {
        this.term = value;
    }

    /**
     * Gets the value of the snapshot property.
     * 
     * @return possible object is {@link ProbeDataManagement.Snapshot }
     */
    public ProbeDataManagement.Snapshot getSnapshot() {
        return snapshot;
    }

    /**
     * Sets the value of the snapshot property.
     * 
     * @param value allowed object is {@link ProbeDataManagement.Snapshot }
     */
    public void setSnapshot(ProbeDataManagement.Snapshot value) {
        this.snapshot = value;
    }

    /**
     * Gets the value of the txInterval property.
     */
    public short getTxInterval() {
        return txInterval;
    }

    /**
     * Sets the value of the txInterval property.
     */
    public void setTxInterval(short value) {
        this.txInterval = value;
    }

    /**
     * Gets the value of the cntTthreshold property.
     */
    public short getCntTthreshold() {
        return cntTthreshold;
    }

    /**
     * Sets the value of the cntTthreshold property.
     */
    public void setCntTthreshold(short value) {
        this.cntTthreshold = value;
    }

    /**
     * Gets the value of the dataElements property.
     * 
     * @return possible object is {@link ProbeDataManagement.DataElements }
     */
    public ProbeDataManagement.DataElements getDataElements() {
        return dataElements;
    }

    /**
     * Sets the value of the dataElements property.
     * 
     * @param value allowed object is {@link ProbeDataManagement.DataElements }
     */
    public void setDataElements(ProbeDataManagement.DataElements value) {
        this.dataElements = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="32">
     *         &lt;element name="VehicleStatusRequest" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleStatusRequest"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "vehicleStatusRequest" })
    public static class DataElements implements Serializable {

        @XmlElement(name = "VehicleStatusRequest", required = true)
        protected List<VehicleStatusRequest> vehicleStatusRequest;

        /**
         * Gets the value of the vehicleStatusRequest property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the vehicleStatusRequest property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getVehicleStatusRequest().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link VehicleStatusRequest }
         */
        public List<VehicleStatusRequest> getVehicleStatusRequest() {
            if (vehicleStatusRequest == null) {
                vehicleStatusRequest = new ArrayList<VehicleStatusRequest>();
            }
            return this.vehicleStatusRequest;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="snapshotTime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SnapshotTime"/>
     *         &lt;element name="snapshotDistance" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SnapshotDistance"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "snapshotTime", "snapshotDistance" })
    public static class Snapshot implements Serializable {

        protected SnapshotTime snapshotTime;

        protected SnapshotDistance snapshotDistance;

        /**
         * Gets the value of the snapshotTime property.
         * 
         * @return possible object is {@link SnapshotTime }
         */
        public SnapshotTime getSnapshotTime() {
            return snapshotTime;
        }

        /**
         * Sets the value of the snapshotTime property.
         * 
         * @param value allowed object is {@link SnapshotTime }
         */
        public void setSnapshotTime(SnapshotTime value) {
            this.snapshotTime = value;
        }

        /**
         * Gets the value of the snapshotDistance property.
         * 
         * @return possible object is {@link SnapshotDistance }
         */
        public SnapshotDistance getSnapshotDistance() {
            return snapshotDistance;
        }

        /**
         * Sets the value of the snapshotDistance property.
         * 
         * @param value allowed object is {@link SnapshotDistance }
         */
        public void setSnapshotDistance(SnapshotDistance value) {
            this.snapshotDistance = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="termtime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TermTime"/>
     *         &lt;element name="termDistance" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TermDistance"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "termtime", "termDistance" })
    public static class Term implements Serializable {

        protected Integer termtime;

        protected Integer termDistance;

        /**
         * Gets the value of the termtime property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getTermtime() {
            return termtime;
        }

        /**
         * Sets the value of the termtime property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setTermtime(Integer value) {
            this.termtime = value;
        }

        /**
         * Gets the value of the termDistance property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getTermDistance() {
            return termDistance;
        }

        /**
         * Sets the value of the termDistance property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setTermDistance(Integer value) {
            this.termDistance = value;
        }

    }

}
