/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RealAssociatedType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RealAssociatedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mantissa" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="base" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="exponent" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealAssociatedType", namespace = "http://www.obj-sys.com/v1.0/XMLSchema", propOrder = { "mantissa", "base", "exponent" })
public class RealAssociatedType implements Serializable {

    @XmlElement(namespace = "", required = true)
    protected BigInteger mantissa;

    @XmlElement(namespace = "", required = true)
    protected BigInteger base;

    @XmlElement(namespace = "", required = true)
    protected BigInteger exponent;

    /**
     * Gets the value of the mantissa property.
     * 
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getMantissa() {
        return mantissa;
    }

    /**
     * Sets the value of the mantissa property.
     * 
     * @param value allowed object is {@link BigInteger }
     */
    public void setMantissa(BigInteger value) {
        this.mantissa = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value allowed object is {@link BigInteger }
     */
    public void setBase(BigInteger value) {
        this.base = value;
    }

    /**
     * Gets the value of the exponent property.
     * 
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getExponent() {
        return exponent;
    }

    /**
     * Sets the value of the exponent property.
     * 
     * @param value allowed object is {@link BigInteger }
     */
    public void setExponent(BigInteger value) {
        this.exponent = value;
    }

}
