/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for RTCM-Corrections complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTCM-Corrections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="msgCnt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}MsgCount"/>
 *         &lt;element name="rev" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCM-Revision"/>
 *         &lt;element name="anchorPoint" type="{http://www.DSRC-Adopted-02-00-36/DSRC}FullPositionVector" minOccurs="0"/>
 *         &lt;element name="rtcmHeader" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCMHeader"/>
 *         &lt;element name="rtcmSets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="5">
 *                   &lt;element name="RTCMmsg" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCMmsg"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTCM-Corrections", propOrder = { "msgID", "msgCnt", "rev", "anchorPoint", "rtcmHeader", "rtcmSets", "any" })
public class RTCMCorrections implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    protected short msgCnt;

    @XmlElement(required = true)
    protected String rev;

    protected FullPositionVector anchorPoint;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] rtcmHeader;

    @XmlElement(required = true)
    protected RTCMCorrections.RtcmSets rtcmSets;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgCnt property.
     */
    public short getMsgCnt() {
        return msgCnt;
    }

    /**
     * Sets the value of the msgCnt property.
     */
    public void setMsgCnt(short value) {
        this.msgCnt = value;
    }

    /**
     * Gets the value of the rev property.
     * 
     * @return possible object is {@link String }
     */
    public String getRev() {
        return rev;
    }

    /**
     * Sets the value of the rev property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRev(String value) {
        this.rev = value;
    }

    /**
     * Gets the value of the anchorPoint property.
     * 
     * @return possible object is {@link FullPositionVector }
     */
    public FullPositionVector getAnchorPoint() {
        return anchorPoint;
    }

    /**
     * Sets the value of the anchorPoint property.
     * 
     * @param value allowed object is {@link FullPositionVector }
     */
    public void setAnchorPoint(FullPositionVector value) {
        this.anchorPoint = value;
    }

    /**
     * Gets the value of the rtcmHeader property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getRtcmHeader() {
        return rtcmHeader.clone();
    }

    /**
     * Sets the value of the rtcmHeader property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRtcmHeader(byte[] value) {
        this.rtcmHeader = ((byte[])value.clone());
    }

    /**
     * Gets the value of the rtcmSets property.
     * 
     * @return possible object is {@link RTCMCorrections.RtcmSets }
     */
    public RTCMCorrections.RtcmSets getRtcmSets() {
        return rtcmSets;
    }

    /**
     * Sets the value of the rtcmSets property.
     * 
     * @param value allowed object is {@link RTCMCorrections.RtcmSets }
     */
    public void setRtcmSets(RTCMCorrections.RtcmSets value) {
        this.rtcmSets = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="5">
     *         &lt;element name="RTCMmsg" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCMmsg"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "rtcMmsg" })
    public static class RtcmSets implements Serializable {

        @XmlElement(name = "RTCMmsg", required = true)
        protected List<RTCMmsg> rtcMmsg;

        /**
         * Gets the value of the rtcMmsg property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the rtcMmsg property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getRTCMmsg().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link RTCMmsg }
         */
        public List<RTCMmsg> getRTCMmsg() {
            if (rtcMmsg == null) {
                rtcMmsg = new ArrayList<RTCMmsg>();
            }
            return this.rtcMmsg;
        }

    }

}
