/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for RTCMPackage complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTCMPackage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anchorPoint" type="{http://www.DSRC-Adopted-02-00-36/DSRC}FullPositionVector" minOccurs="0"/>
 *         &lt;element name="rtcmHeader" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCMHeader"/>
 *         &lt;element name="msg1001" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="16"/>
 *               &lt;maxLength value="124"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1002" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="18"/>
 *               &lt;maxLength value="156"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1003" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="21"/>
 *               &lt;maxLength value="210"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1004" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="24"/>
 *               &lt;maxLength value="258"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1005" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1006" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="21"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1007" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="36"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1008" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="6"/>
 *               &lt;maxLength value="68"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1009" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="16"/>
 *               &lt;maxLength value="136"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1010" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="18"/>
 *               &lt;maxLength value="166"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1011" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="21"/>
 *               &lt;maxLength value="222"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1012" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="24"/>
 *               &lt;maxLength value="268"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1013" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="13"/>
 *               &lt;maxLength value="27"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1014" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1015" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="13"/>
 *               &lt;maxLength value="69"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1016" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="14"/>
 *               &lt;maxLength value="81"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1017" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="16"/>
 *               &lt;maxLength value="115"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1019" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="62"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1020" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="45"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1021" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="62"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1022" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="75"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1023" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="73"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1024" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="74"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1025" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1026" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1027" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="33"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1029" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="10"/>
 *               &lt;maxLength value="69"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1030" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="14"/>
 *               &lt;maxLength value="105"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1031" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;minLength value="15"/>
 *               &lt;maxLength value="107"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="msg1032" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}hexBinary">
 *               &lt;length value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTCMPackage", propOrder = { "anchorPoint", "rtcmHeader", "msg1001", "msg1002", "msg1003", "msg1004", "msg1005", "msg1006", "msg1007", "msg1008", "msg1009", "msg1010", "msg1011",
        "msg1012", "msg1013", "msg1014", "msg1015", "msg1016", "msg1017", "msg1019", "msg1020", "msg1021", "msg1022", "msg1023", "msg1024", "msg1025", "msg1026", "msg1027", "msg1029", "msg1030",
        "msg1031", "msg1032", "any" })
public class RTCMPackage implements Serializable {

    protected FullPositionVector anchorPoint;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] rtcmHeader;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1001;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1002;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1003;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1004;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1005;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1006;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1007;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1008;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1009;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1010;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1011;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1012;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1013;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1014;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1015;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1016;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1017;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1019;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1020;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1021;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1022;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1023;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1024;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1025;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1026;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1027;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1029;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1030;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1031;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] msg1032;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the anchorPoint property.
     * 
     * @return possible object is {@link FullPositionVector }
     */
    public FullPositionVector getAnchorPoint() {
        return anchorPoint;
    }

    /**
     * Sets the value of the anchorPoint property.
     * 
     * @param value allowed object is {@link FullPositionVector }
     */
    public void setAnchorPoint(FullPositionVector value) {
        this.anchorPoint = value;
    }

    /**
     * Gets the value of the rtcmHeader property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getRtcmHeader() {
        return rtcmHeader == null ? null : rtcmHeader.clone();
    }

    /**
     * Sets the value of the rtcmHeader property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRtcmHeader(byte[] value) {
        this.rtcmHeader = ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1001 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1001() {
        return msg1001 == null ? null : msg1001.clone();
    }

    /**
     * Sets the value of the msg1001 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1001(byte[] value) {
        this.msg1001 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1002 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1002() {
        return msg1002 == null ? null : msg1002.clone();
    }

    /**
     * Sets the value of the msg1002 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1002(byte[] value) {
        this.msg1002 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1003 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1003() {
        return msg1003 == null ? null : msg1003.clone();
    }

    /**
     * Sets the value of the msg1003 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1003(byte[] value) {
        this.msg1003 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1004 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1004() {
        return msg1004 == null ? null : msg1004.clone();
    }

    /**
     * Sets the value of the msg1004 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1004(byte[] value) {
        this.msg1004 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1005 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1005() {
        return msg1005 == null ? null : msg1005.clone();
    }

    /**
     * Sets the value of the msg1005 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1005(byte[] value) {
        this.msg1005 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1006 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1006() {
        return msg1006 == null ? null : msg1006.clone();
    }

    /**
     * Sets the value of the msg1006 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1006(byte[] value) {
        this.msg1006 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1007 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1007() {
        return msg1007 == null ? null : msg1007.clone();
    }

    /**
     * Sets the value of the msg1007 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1007(byte[] value) {
        this.msg1007 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1008 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1008() {
        return msg1008 == null ? null : msg1008.clone();
    }

    /**
     * Sets the value of the msg1008 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1008(byte[] value) {
        this.msg1008 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1009 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1009() {
        return msg1009 == null ? null : msg1009.clone();
    }

    /**
     * Sets the value of the msg1009 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1009(byte[] value) {
        this.msg1009 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1010 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1010() {
        return msg1010 == null ? null : msg1010.clone();
    }

    /**
     * Sets the value of the msg1010 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1010(byte[] value) {
        this.msg1010 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1011 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1011() {
        return msg1011 == null ? null : msg1011.clone();
    }

    /**
     * Sets the value of the msg1011 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1011(byte[] value) {
        this.msg1011 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1012 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1012() {
        return msg1012 == null ? null : msg1012.clone();
    }

    /**
     * Sets the value of the msg1012 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1012(byte[] value) {
        this.msg1012 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1013 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1013() {
        return msg1013 == null ? null : msg1013.clone();
    }

    /**
     * Sets the value of the msg1013 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1013(byte[] value) {
        this.msg1013 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1014 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1014() {
        return msg1014 == null ? null : msg1014.clone();
    }

    /**
     * Sets the value of the msg1014 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1014(byte[] value) {
        this.msg1014 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1015 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1015() {
        return msg1015 == null ? null : msg1015.clone();
    }

    /**
     * Sets the value of the msg1015 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1015(byte[] value) {
        this.msg1015 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1016 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1016() {
        return msg1016 == null ? null : msg1016.clone();
    }

    /**
     * Sets the value of the msg1016 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1016(byte[] value) {
        this.msg1016 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1017 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1017() {
        return msg1017 == null ? null : msg1017.clone();
    }

    /**
     * Sets the value of the msg1017 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1017(byte[] value) {
        this.msg1017 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1019 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1019() {
        return msg1019 == null ? null : msg1019.clone();
    }

    /**
     * Sets the value of the msg1019 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1019(byte[] value) {
        this.msg1019 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1020 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1020() {
        return msg1020 == null ? null : msg1020.clone();
    }

    /**
     * Sets the value of the msg1020 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1020(byte[] value) {
        this.msg1020 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1021 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1021() {
        return msg1021 == null ? null : msg1021.clone();
    }

    /**
     * Sets the value of the msg1021 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1021(byte[] value) {
        this.msg1021 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1022 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1022() {
        return msg1022 == null ? null : msg1022.clone();
    }

    /**
     * Sets the value of the msg1022 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1022(byte[] value) {
        this.msg1022 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1023 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1023() {
        return msg1023 == null ? null : msg1023.clone();
    }

    /**
     * Sets the value of the msg1023 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1023(byte[] value) {
        this.msg1023 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1024 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1024() {
        return msg1024 == null ? null : msg1024.clone();
    }

    /**
     * Sets the value of the msg1024 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1024(byte[] value) {
        this.msg1024 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1025 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1025() {
        return msg1025 == null ? null : msg1025.clone();
    }

    /**
     * Sets the value of the msg1025 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1025(byte[] value) {
        this.msg1025 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1026 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1026() {
        return msg1026 == null ? null : msg1026.clone();
    }

    /**
     * Sets the value of the msg1026 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1026(byte[] value) {
        this.msg1026 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1027 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1027() {
        return msg1027 == null ? null : msg1027.clone();
    }

    /**
     * Sets the value of the msg1027 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1027(byte[] value) {
        this.msg1027 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1029 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1029() {
        return msg1029 == null ? null : msg1029.clone();
    }

    /**
     * Sets the value of the msg1029 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1029(byte[] value) {
        this.msg1029 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1030 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1030() {
        return msg1030 == null ? null : msg1030.clone();
    }

    /**
     * Sets the value of the msg1030 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1030(byte[] value) {
        this.msg1030 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1031 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1031() {
        return msg1031 == null ? null : msg1031.clone();
    }

    /**
     * Sets the value of the msg1031 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1031(byte[] value) {
        this.msg1031 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the msg1032 property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getMsg1032() {
        return msg1032 == null ? null : msg1032.clone();
    }

    /**
     * Sets the value of the msg1032 property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsg1032(byte[] value) {
        this.msg1032 = value == null ? null : ((byte[])value.clone());
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
