/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for SignalStatusMessage complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalStatusMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgID" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DSRCmsgID"/>
 *         &lt;element name="msgCnt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}MsgCount"/>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionID"/>
 *         &lt;element name="status" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionStatusObject"/>
 *         &lt;element name="priority" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction>
 *               &lt;simpleType>
 *                 &lt;list itemType="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalState" />
 *               &lt;/simpleType>
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="priorityCause" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleIdent" minOccurs="0"/>
 *         &lt;element name="prempt" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction>
 *               &lt;simpleType>
 *                 &lt;list itemType="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalState" />
 *               &lt;/simpleType>
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="preemptCause" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleIdent" minOccurs="0"/>
 *         &lt;element name="transitStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TransitStatus" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalStatusMessage", propOrder = { "msgID", "msgCnt", "id", "status", "priority", "priorityCause", "prempt", "preemptCause", "transitStatus", "any" })
public class SignalStatusMessage implements Serializable {

    @XmlElement(required = true)
    protected String msgID;

    protected short msgCnt;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] id;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] status;

    @XmlList
    protected List<String> priority;

    protected VehicleIdent priorityCause;

    @XmlList
    protected List<String> prempt;

    protected VehicleIdent preemptCause;

    @XmlList
    protected List<String> transitStatus;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the msgID property.
     * 
     * @return possible object is {@link String }
     */
    public String getMsgID() {
        return msgID;
    }

    /**
     * Sets the value of the msgID property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setMsgID(String value) {
        this.msgID = value;
    }

    /**
     * Gets the value of the msgCnt property.
     */
    public short getMsgCnt() {
        return msgCnt;
    }

    /**
     * Sets the value of the msgCnt property.
     */
    public void setMsgCnt(short value) {
        this.msgCnt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getId() {
        return id.clone();
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(byte[] value) {
        this.id = ((byte[])value.clone());
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getStatus() {
        return status.clone();
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStatus(byte[] value) {
        this.status = ((byte[])value.clone());
    }

    /**
     * Gets the value of the priority property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the priority property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPriority().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getPriority() {
        if (priority == null) {
            priority = new ArrayList<String>();
        }
        return this.priority;
    }

    /**
     * Gets the value of the priorityCause property.
     * 
     * @return possible object is {@link VehicleIdent }
     */
    public VehicleIdent getPriorityCause() {
        return priorityCause;
    }

    /**
     * Sets the value of the priorityCause property.
     * 
     * @param value allowed object is {@link VehicleIdent }
     */
    public void setPriorityCause(VehicleIdent value) {
        this.priorityCause = value;
    }

    /**
     * Gets the value of the prempt property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the prempt property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPrempt().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getPrempt() {
        if (prempt == null) {
            prempt = new ArrayList<String>();
        }
        return this.prempt;
    }

    /**
     * Gets the value of the preemptCause property.
     * 
     * @return possible object is {@link VehicleIdent }
     */
    public VehicleIdent getPreemptCause() {
        return preemptCause;
    }

    /**
     * Sets the value of the preemptCause property.
     * 
     * @param value allowed object is {@link VehicleIdent }
     */
    public void setPreemptCause(VehicleIdent value) {
        this.preemptCause = value;
    }

    /**
     * Gets the value of the transitStatus property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the transitStatus property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getTransitStatus().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getTransitStatus() {
        if (transitStatus == null) {
            transitStatus = new ArrayList<String>();
        }
        return this.transitStatus;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
