/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for SignalRequest complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.DSRC-Adopted-02-00-36/DSRC}IntersectionID"/>
 *         &lt;element name="isCancel" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalReqScheme" minOccurs="0"/>
 *         &lt;element name="requestedAction" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SignalReqScheme" minOccurs="0"/>
 *         &lt;element name="inLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneNumber" minOccurs="0"/>
 *         &lt;element name="outLane" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LaneNumber" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.DSRC-Adopted-02-00-36/DSRC}NTCIPVehicleclass"/>
 *         &lt;element name="codeWord" type="{http://www.DSRC-Adopted-02-00-36/DSRC}CodeWord" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalRequest", propOrder = { "id", "isCancel", "requestedAction", "inLane", "outLane", "type", "codeWord", "any" })
public class SignalRequest implements Serializable {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] id;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] isCancel;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] requestedAction;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] inLane;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] outLane;

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] type;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] codeWord;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getId() {
        return id.clone();
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setId(byte[] value) {
        this.id = ((byte[])value.clone());
    }

    /**
     * Gets the value of the isCancel property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getIsCancel() {
        return isCancel.clone();
    }

    /**
     * Sets the value of the isCancel property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setIsCancel(byte[] value) {
        this.isCancel = ((byte[])value.clone());
    }

    /**
     * Gets the value of the requestedAction property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getRequestedAction() {
        return requestedAction.clone();
    }

    /**
     * Sets the value of the requestedAction property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setRequestedAction(byte[] value) {
        this.requestedAction = ((byte[])value.clone());
    }

    /**
     * Gets the value of the inLane property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getInLane() {
        return inLane.clone();
    }

    /**
     * Sets the value of the inLane property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setInLane(byte[] value) {
        this.inLane = ((byte[])value.clone());
    }

    /**
     * Gets the value of the outLane property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getOutLane() {
        return outLane.clone();
    }

    /**
     * Sets the value of the outLane property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setOutLane(byte[] value) {
        this.outLane = ((byte[])value.clone());
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getType() {
        return type.clone();
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setType(byte[] value) {
        this.type = ((byte[])value.clone());
    }

    /**
     * Gets the value of the codeWord property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getCodeWord() {
        return codeWord.clone();
    }

    /**
     * Sets the value of the codeWord property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCodeWord(byte[] value) {
        this.codeWord = ((byte[])value.clone());
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
