/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for Snapshot complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Snapshot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="thePosition" type="{http://www.DSRC-Adopted-02-00-36/DSRC}FullPositionVector"/>
 *         &lt;element name="safetyExt" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleSafetyExtension" minOccurs="0"/>
 *         &lt;element name="datSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleStatus" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Snapshot", propOrder = { "thePosition", "safetyExt", "datSet", "any" })
public class Snapshot implements Serializable {

    @XmlElement(required = true)
    protected FullPositionVector thePosition;

    protected VehicleSafetyExtension safetyExt;

    protected VehicleStatus datSet;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the thePosition property.
     * 
     * @return possible object is {@link FullPositionVector }
     */
    public FullPositionVector getThePosition() {
        return thePosition;
    }

    /**
     * Sets the value of the thePosition property.
     * 
     * @param value allowed object is {@link FullPositionVector }
     */
    public void setThePosition(FullPositionVector value) {
        this.thePosition = value;
    }

    /**
     * Gets the value of the safetyExt property.
     * 
     * @return possible object is {@link VehicleSafetyExtension }
     */
    public VehicleSafetyExtension getSafetyExt() {
        return safetyExt;
    }

    /**
     * Sets the value of the safetyExt property.
     * 
     * @param value allowed object is {@link VehicleSafetyExtension }
     */
    public void setSafetyExt(VehicleSafetyExtension value) {
        this.safetyExt = value;
    }

    /**
     * Gets the value of the datSet property.
     * 
     * @return possible object is {@link VehicleStatus }
     */
    public VehicleStatus getDatSet() {
        return datSet;
    }

    /**
     * Sets the value of the datSet property.
     * 
     * @param value allowed object is {@link VehicleStatus }
     */
    public void setDatSet(VehicleStatus value) {
        this.datSet = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
