/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SpecialLaneAttributes.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="SpecialLaneAttributes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="noData"/>
 *     &lt;enumeration value="egressPath"/>
 *     &lt;enumeration value="railRoadTrack"/>
 *     &lt;enumeration value="transitOnlyLane"/>
 *     &lt;enumeration value="hovLane"/>
 *     &lt;enumeration value="busOnly"/>
 *     &lt;enumeration value="vehiclesEntering"/>
 *     &lt;enumeration value="vehiclesLeaving"/>
 *     &lt;enumeration value="reserved"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "SpecialLaneAttributes")
@XmlEnum
public enum SpecialLaneAttributes {

    @XmlEnumValue("noData")
    NO_DATA("noData"),
    @XmlEnumValue("egressPath")
    EGRESS_PATH("egressPath"),
    @XmlEnumValue("railRoadTrack")
    RAIL_ROAD_TRACK("railRoadTrack"),
    @XmlEnumValue("transitOnlyLane")
    TRANSIT_ONLY_LANE("transitOnlyLane"),
    @XmlEnumValue("hovLane")
    HOV_LANE("hovLane"),
    @XmlEnumValue("busOnly")
    BUS_ONLY("busOnly"),
    @XmlEnumValue("vehiclesEntering")
    VEHICLES_ENTERING("vehiclesEntering"),
    @XmlEnumValue("vehiclesLeaving")
    VEHICLES_LEAVING("vehiclesLeaving"),
    @XmlEnumValue("reserved")
    RESERVED("reserved");

    private final String value;

    SpecialLaneAttributes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpecialLaneAttributes fromValue(String v) {
        for (SpecialLaneAttributes c : SpecialLaneAttributes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
