/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SpeedConfidence.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="SpeedConfidence">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="unavailable"/>
 *     &lt;enumeration value="prec100ms"/>
 *     &lt;enumeration value="prec10ms"/>
 *     &lt;enumeration value="prec5ms"/>
 *     &lt;enumeration value="prec1ms"/>
 *     &lt;enumeration value="prec0-1ms"/>
 *     &lt;enumeration value="prec0-05ms"/>
 *     &lt;enumeration value="prec0-01ms"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "SpeedConfidence")
@XmlEnum
public enum SpeedConfidence {

    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable"),
    @XmlEnumValue("prec100ms")
    PREC_100_MS("prec100ms"),
    @XmlEnumValue("prec10ms")
    PREC_10_MS("prec10ms"),
    @XmlEnumValue("prec5ms")
    PREC_5_MS("prec5ms"),
    @XmlEnumValue("prec1ms")
    PREC_1_MS("prec1ms"),
    @XmlEnumValue("prec0-1ms")
    PREC_0_1_MS("prec0-1ms"),
    @XmlEnumValue("prec0-05ms")
    PREC_0_05_MS("prec0-05ms"),
    @XmlEnumValue("prec0-01ms")
    PREC_0_01_MS("prec0-01ms");

    private final String value;

    SpeedConfidence(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpeedConfidence fromValue(String v) {
        for (SpeedConfidence c : SpeedConfidence.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
