/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for ValidRegion complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidRegion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="direction" type="{http://www.DSRC-Adopted-02-00-36/DSRC}HeadingSlice"/>
 *         &lt;element name="extent" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Extent" minOccurs="0"/>
 *         &lt;element name="area">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="shapePointSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ShapePointSet"/>
 *                   &lt;element name="circle" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Circle"/>
 *                   &lt;element name="regionPointSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RegionPointSet"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidRegion", propOrder = { "direction", "extent", "area" })
public class ValidRegion implements Serializable {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] direction;

    protected Extent extent;

    @XmlElement(required = true)
    protected ValidRegion.Area area;

    /**
     * Gets the value of the direction property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getDirection() {
        return direction.clone();
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setDirection(byte[] value) {
        this.direction = ((byte[])value.clone());
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return possible object is {@link Extent }
     */
    public Extent getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value allowed object is {@link Extent }
     */
    public void setExtent(Extent value) {
        this.extent = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return possible object is {@link ValidRegion.Area }
     */
    public ValidRegion.Area getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value allowed object is {@link ValidRegion.Area }
     */
    public void setArea(ValidRegion.Area value) {
        this.area = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="shapePointSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ShapePointSet"/>
     *         &lt;element name="circle" type="{http://www.DSRC-Adopted-02-00-36/DSRC}Circle"/>
     *         &lt;element name="regionPointSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RegionPointSet"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "shapePointSet", "circle", "regionPointSet" })
    public static class Area implements Serializable {

        protected ShapePointSet shapePointSet;

        protected Circle circle;

        protected RegionPointSet regionPointSet;

        /**
         * Gets the value of the shapePointSet property.
         * 
         * @return possible object is {@link ShapePointSet }
         */
        public ShapePointSet getShapePointSet() {
            return shapePointSet;
        }

        /**
         * Sets the value of the shapePointSet property.
         * 
         * @param value allowed object is {@link ShapePointSet }
         */
        public void setShapePointSet(ShapePointSet value) {
            this.shapePointSet = value;
        }

        /**
         * Gets the value of the circle property.
         * 
         * @return possible object is {@link Circle }
         */
        public Circle getCircle() {
            return circle;
        }

        /**
         * Sets the value of the circle property.
         * 
         * @param value allowed object is {@link Circle }
         */
        public void setCircle(Circle value) {
            this.circle = value;
        }

        /**
         * Gets the value of the regionPointSet property.
         * 
         * @return possible object is {@link RegionPointSet }
         */
        public RegionPointSet getRegionPointSet() {
            return regionPointSet;
        }

        /**
         * Sets the value of the regionPointSet property.
         * 
         * @param value allowed object is {@link RegionPointSet }
         */
        public void setRegionPointSet(RegionPointSet value) {
            this.regionPointSet = value;
        }

    }

}
