/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for VehicleSafetyExtension complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleSafetyExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="events" type="{http://www.DSRC-Adopted-02-00-36/DSRC}EventFlags" minOccurs="0"/>
 *         &lt;element name="pathHistory" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PathHistory" minOccurs="0"/>
 *         &lt;element name="pathPrediction" type="{http://www.DSRC-Adopted-02-00-36/DSRC}PathPrediction" minOccurs="0"/>
 *         &lt;element name="theRTCM" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RTCMPackage" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleSafetyExtension", propOrder = { "events", "pathHistory", "pathPrediction", "theRTCM", "any" })
public class VehicleSafetyExtension implements Serializable {

    protected Integer events;

    protected PathHistory pathHistory;

    protected PathPrediction pathPrediction;

    protected RTCMPackage theRTCM;

    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the events property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setEvents(Integer value) {
        this.events = value;
    }

    /**
     * Gets the value of the pathHistory property.
     * 
     * @return possible object is {@link PathHistory }
     */
    public PathHistory getPathHistory() {
        return pathHistory;
    }

    /**
     * Sets the value of the pathHistory property.
     * 
     * @param value allowed object is {@link PathHistory }
     */
    public void setPathHistory(PathHistory value) {
        this.pathHistory = value;
    }

    /**
     * Gets the value of the pathPrediction property.
     * 
     * @return possible object is {@link PathPrediction }
     */
    public PathPrediction getPathPrediction() {
        return pathPrediction;
    }

    /**
     * Sets the value of the pathPrediction property.
     * 
     * @param value allowed object is {@link PathPrediction }
     */
    public void setPathPrediction(PathPrediction value) {
        this.pathPrediction = value;
    }

    /**
     * Gets the value of the theRTCM property.
     * 
     * @return possible object is {@link RTCMPackage }
     */
    public RTCMPackage getTheRTCM() {
        return theRTCM;
    }

    /**
     * Sets the value of the theRTCM property.
     * 
     * @param value allowed object is {@link RTCMPackage }
     */
    public void setTheRTCM(RTCMPackage value) {
        this.theRTCM = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
