/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for VehicleStatus complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lights" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ExteriorLights" minOccurs="0"/>
 *         &lt;element name="lightBar" type="{http://www.DSRC-Adopted-02-00-36/DSRC}LightbarInUse" minOccurs="0"/>
 *         &lt;element name="wipers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="statusFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusFront"/>
 *                   &lt;element name="rateFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate"/>
 *                   &lt;element name="statusRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusRear" minOccurs="0"/>
 *                   &lt;element name="rateRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="brakeStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BrakeSystemStatus" minOccurs="0"/>
 *         &lt;element name="brakePressure" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BrakeAppliedPressure" minOccurs="0"/>
 *         &lt;element name="roadFriction" type="{http://www.DSRC-Adopted-02-00-36/DSRC}CoefficientOfFriction" minOccurs="0"/>
 *         &lt;element name="sunData" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SunSensor" minOccurs="0"/>
 *         &lt;element name="rainData" type="{http://www.DSRC-Adopted-02-00-36/DSRC}RainSensor" minOccurs="0"/>
 *         &lt;element name="airTemp" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AmbientAirTemperature" minOccurs="0"/>
 *         &lt;element name="airPres" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AmbientAirPressure" minOccurs="0"/>
 *         &lt;element name="steering" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="angle" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngle"/>
 *                   &lt;element name="confidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngleConfidence" minOccurs="0"/>
 *                   &lt;element name="rate" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngleRateOfChange" minOccurs="0"/>
 *                   &lt;element name="wheels" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DrivingWheelAngle" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accelSets" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accel4way" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelerationSet4Way" minOccurs="0"/>
 *                   &lt;element name="vertAccelThres" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VerticalAccelerationThreshold" minOccurs="0"/>
 *                   &lt;element name="yawRateCon" type="{http://www.DSRC-Adopted-02-00-36/DSRC}YawRateConfidence" minOccurs="0"/>
 *                   &lt;element name="hozAccelCon" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelerationConfidence" minOccurs="0"/>
 *                   &lt;element name="confidenceSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ConfidenceSet" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="object" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="obDist" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObstacleDistance"/>
 *                   &lt;element name="obDirect" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObstacleDirection"/>
 *                   &lt;element name="dateTime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DDateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fullPos" type="{http://www.DSRC-Adopted-02-00-36/DSRC}FullPositionVector" minOccurs="0"/>
 *         &lt;element name="throttlePos" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ThrottlePosition" minOccurs="0"/>
 *         &lt;element name="speedHeadC" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpeedandHeadingandThrottleConfidence" minOccurs="0"/>
 *         &lt;element name="speedC" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SpeedConfidence" minOccurs="0"/>
 *         &lt;element name="vehicleData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="height" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleHeight"/>
 *                   &lt;element name="bumpers" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BumperHeights"/>
 *                   &lt;element name="mass" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleMass"/>
 *                   &lt;element name="trailerWeight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TrailerWeight"/>
 *                   &lt;element name="type" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vehicleIdent" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleIdent" minOccurs="0"/>
 *         &lt;element name="j1939data" type="{http://www.DSRC-Adopted-02-00-36/DSRC}J1939data" minOccurs="0"/>
 *         &lt;element name="weatherReport" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isRaining" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipYesNo"/>
 *                   &lt;element name="rainRate" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipRate" minOccurs="0"/>
 *                   &lt;element name="precipSituation" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipSituation" minOccurs="0"/>
 *                   &lt;element name="solarRadiation" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssSolarRadiation" minOccurs="0"/>
 *                   &lt;element name="friction" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssMobileFriction" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gpsStatus" type="{http://www.DSRC-Adopted-02-00-36/DSRC}GPSstatus" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleStatus", propOrder = { "lights", "lightBar", "wipers", "brakeStatus", "brakePressure", "roadFriction", "sunData", "rainData", "airTemp", "airPres", "steering", "accelSets",
        "object", "fullPos", "throttlePos", "speedHeadC", "speedC", "vehicleData", "vehicleIdent", "j1939Data", "weatherReport", "gpsStatus", "any" })
public class VehicleStatus implements Serializable {

    protected Integer lights;

    protected LightbarInUse lightBar;

    protected VehicleStatus.Wipers wipers;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] brakeStatus;

    protected BrakeAppliedPressure brakePressure;

    protected Short roadFriction;

    protected Integer sunData;

    protected RainSensor rainData;

    protected Short airTemp;

    protected Short airPres;

    protected VehicleStatus.Steering steering;

    protected VehicleStatus.AccelSets accelSets;

    protected VehicleStatus.Object object;

    protected FullPositionVector fullPos;

    protected Short throttlePos;

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] speedHeadC;

    protected SpeedConfidence speedC;

    protected VehicleStatus.VehicleData vehicleData;

    protected VehicleIdent vehicleIdent;

    @XmlElement(name = "j1939data")
    protected J1939Data j1939Data;

    protected VehicleStatus.WeatherReport weatherReport;

    @XmlList
    protected List<String> gpsStatus;

    @XmlAnyElement(lax = true)
    protected java.lang.Object any;

    /**
     * Gets the value of the lights property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getLights() {
        return lights;
    }

    /**
     * Sets the value of the lights property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setLights(Integer value) {
        this.lights = value;
    }

    /**
     * Gets the value of the lightBar property.
     * 
     * @return possible object is {@link LightbarInUse }
     */
    public LightbarInUse getLightBar() {
        return lightBar;
    }

    /**
     * Sets the value of the lightBar property.
     * 
     * @param value allowed object is {@link LightbarInUse }
     */
    public void setLightBar(LightbarInUse value) {
        this.lightBar = value;
    }

    /**
     * Gets the value of the wipers property.
     * 
     * @return possible object is {@link VehicleStatus.Wipers }
     */
    public VehicleStatus.Wipers getWipers() {
        return wipers;
    }

    /**
     * Sets the value of the wipers property.
     * 
     * @param value allowed object is {@link VehicleStatus.Wipers }
     */
    public void setWipers(VehicleStatus.Wipers value) {
        this.wipers = value;
    }

    /**
     * Gets the value of the brakeStatus property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getBrakeStatus() {
        return brakeStatus == null ? null : brakeStatus.clone();
    }

    /**
     * Sets the value of the brakeStatus property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setBrakeStatus(byte[] value) {
        this.brakeStatus = ((byte[])value.clone());
    }

    /**
     * Gets the value of the brakePressure property.
     * 
     * @return possible object is {@link BrakeAppliedPressure }
     */
    public BrakeAppliedPressure getBrakePressure() {
        return brakePressure;
    }

    /**
     * Sets the value of the brakePressure property.
     * 
     * @param value allowed object is {@link BrakeAppliedPressure }
     */
    public void setBrakePressure(BrakeAppliedPressure value) {
        this.brakePressure = value;
    }

    /**
     * Gets the value of the roadFriction property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getRoadFriction() {
        return roadFriction;
    }

    /**
     * Sets the value of the roadFriction property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setRoadFriction(Short value) {
        this.roadFriction = value;
    }

    /**
     * Gets the value of the sunData property.
     * 
     * @return possible object is {@link Integer }
     */
    public Integer getSunData() {
        return sunData;
    }

    /**
     * Sets the value of the sunData property.
     * 
     * @param value allowed object is {@link Integer }
     */
    public void setSunData(Integer value) {
        this.sunData = value;
    }

    /**
     * Gets the value of the rainData property.
     * 
     * @return possible object is {@link RainSensor }
     */
    public RainSensor getRainData() {
        return rainData;
    }

    /**
     * Sets the value of the rainData property.
     * 
     * @param value allowed object is {@link RainSensor }
     */
    public void setRainData(RainSensor value) {
        this.rainData = value;
    }

    /**
     * Gets the value of the airTemp property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getAirTemp() {
        return airTemp;
    }

    /**
     * Sets the value of the airTemp property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setAirTemp(Short value) {
        this.airTemp = value;
    }

    /**
     * Gets the value of the airPres property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getAirPres() {
        return airPres;
    }

    /**
     * Sets the value of the airPres property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setAirPres(Short value) {
        this.airPres = value;
    }

    /**
     * Gets the value of the steering property.
     * 
     * @return possible object is {@link VehicleStatus.Steering }
     */
    public VehicleStatus.Steering getSteering() {
        return steering;
    }

    /**
     * Sets the value of the steering property.
     * 
     * @param value allowed object is {@link VehicleStatus.Steering }
     */
    public void setSteering(VehicleStatus.Steering value) {
        this.steering = value;
    }

    /**
     * Gets the value of the accelSets property.
     * 
     * @return possible object is {@link VehicleStatus.AccelSets }
     */
    public VehicleStatus.AccelSets getAccelSets() {
        return accelSets;
    }

    /**
     * Sets the value of the accelSets property.
     * 
     * @param value allowed object is {@link VehicleStatus.AccelSets }
     */
    public void setAccelSets(VehicleStatus.AccelSets value) {
        this.accelSets = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return possible object is {@link VehicleStatus.Object }
     */
    public VehicleStatus.Object getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value allowed object is {@link VehicleStatus.Object }
     */
    public void setObject(VehicleStatus.Object value) {
        this.object = value;
    }

    /**
     * Gets the value of the fullPos property.
     * 
     * @return possible object is {@link FullPositionVector }
     */
    public FullPositionVector getFullPos() {
        return fullPos;
    }

    /**
     * Sets the value of the fullPos property.
     * 
     * @param value allowed object is {@link FullPositionVector }
     */
    public void setFullPos(FullPositionVector value) {
        this.fullPos = value;
    }

    /**
     * Gets the value of the throttlePos property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getThrottlePos() {
        return throttlePos;
    }

    /**
     * Sets the value of the throttlePos property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setThrottlePos(Short value) {
        this.throttlePos = value;
    }

    /**
     * Gets the value of the speedHeadC property.
     * 
     * @return possible object is {@link String }
     */
    public byte[] getSpeedHeadC() {
        return speedHeadC == null ? null : speedHeadC.clone();
    }

    /**
     * Sets the value of the speedHeadC property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setSpeedHeadC(byte[] value) {
        this.speedHeadC = ((byte[])value.clone());
    }

    /**
     * Gets the value of the speedC property.
     * 
     * @return possible object is {@link SpeedConfidence }
     */
    public SpeedConfidence getSpeedC() {
        return speedC;
    }

    /**
     * Sets the value of the speedC property.
     * 
     * @param value allowed object is {@link SpeedConfidence }
     */
    public void setSpeedC(SpeedConfidence value) {
        this.speedC = value;
    }

    /**
     * Gets the value of the vehicleData property.
     * 
     * @return possible object is {@link VehicleStatus.VehicleData }
     */
    public VehicleStatus.VehicleData getVehicleData() {
        return vehicleData;
    }

    /**
     * Sets the value of the vehicleData property.
     * 
     * @param value allowed object is {@link VehicleStatus.VehicleData }
     */
    public void setVehicleData(VehicleStatus.VehicleData value) {
        this.vehicleData = value;
    }

    /**
     * Gets the value of the vehicleIdent property.
     * 
     * @return possible object is {@link VehicleIdent }
     */
    public VehicleIdent getVehicleIdent() {
        return vehicleIdent;
    }

    /**
     * Sets the value of the vehicleIdent property.
     * 
     * @param value allowed object is {@link VehicleIdent }
     */
    public void setVehicleIdent(VehicleIdent value) {
        this.vehicleIdent = value;
    }

    /**
     * Gets the value of the j1939Data property.
     * 
     * @return possible object is {@link J1939Data }
     */
    public J1939Data getJ1939Data() {
        return j1939Data;
    }

    /**
     * Sets the value of the j1939Data property.
     * 
     * @param value allowed object is {@link J1939Data }
     */
    public void setJ1939Data(J1939Data value) {
        this.j1939Data = value;
    }

    /**
     * Gets the value of the weatherReport property.
     * 
     * @return possible object is {@link VehicleStatus.WeatherReport }
     */
    public VehicleStatus.WeatherReport getWeatherReport() {
        return weatherReport;
    }

    /**
     * Sets the value of the weatherReport property.
     * 
     * @param value allowed object is {@link VehicleStatus.WeatherReport }
     */
    public void setWeatherReport(VehicleStatus.WeatherReport value) {
        this.weatherReport = value;
    }

    /**
     * Gets the value of the gpsStatus property.
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the gpsStatus property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getGpsStatus().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     */
    public List<String> getGpsStatus() {
        if (gpsStatus == null) {
            gpsStatus = new ArrayList<String>();
        }
        return this.gpsStatus;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return possible object is {@link Element } {@link java.lang.Object }
     */
    public java.lang.Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value allowed object is {@link Element } {@link java.lang.Object }
     */
    public void setAny(java.lang.Object value) {
        this.any = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="accel4way" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelerationSet4Way" minOccurs="0"/>
     *         &lt;element name="vertAccelThres" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VerticalAccelerationThreshold" minOccurs="0"/>
     *         &lt;element name="yawRateCon" type="{http://www.DSRC-Adopted-02-00-36/DSRC}YawRateConfidence" minOccurs="0"/>
     *         &lt;element name="hozAccelCon" type="{http://www.DSRC-Adopted-02-00-36/DSRC}AccelerationConfidence" minOccurs="0"/>
     *         &lt;element name="confidenceSet" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ConfidenceSet" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "accel4Way", "vertAccelThres", "yawRateCon", "hozAccelCon", "confidenceSet" })
    public static class AccelSets implements Serializable {

        @XmlElement(name = "accel4way", type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        protected byte[] accel4Way;

        @XmlList
        protected List<String> vertAccelThres;

        protected YawRateConfidence yawRateCon;

        protected AccelerationConfidence hozAccelCon;

        protected ConfidenceSet confidenceSet;

        /**
         * Gets the value of the accel4Way property.
         * 
         * @return possible object is {@link String }
         */
        public byte[] getAccel4Way() {
            return accel4Way.clone();
        }

        /**
         * Sets the value of the accel4Way property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setAccel4Way(byte[] value) {
            this.accel4Way = ((byte[])value.clone());
        }

        /**
         * Gets the value of the vertAccelThres property.
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any
         * modification you make to the returned list will be present inside the JAXB object. This
         * is why there is not a <CODE>set</CODE> method for the vertAccelThres property.
         * <p>
         * For example, to add a new item, do as follows:
         * 
         * <pre>
         * getVertAccelThres().add(newItem);
         * </pre>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link String }
         */
        public List<String> getVertAccelThres() {
            if (vertAccelThres == null) {
                vertAccelThres = new ArrayList<String>();
            }
            return this.vertAccelThres;
        }

        /**
         * Gets the value of the yawRateCon property.
         * 
         * @return possible object is {@link YawRateConfidence }
         */
        public YawRateConfidence getYawRateCon() {
            return yawRateCon;
        }

        /**
         * Sets the value of the yawRateCon property.
         * 
         * @param value allowed object is {@link YawRateConfidence }
         */
        public void setYawRateCon(YawRateConfidence value) {
            this.yawRateCon = value;
        }

        /**
         * Gets the value of the hozAccelCon property.
         * 
         * @return possible object is {@link AccelerationConfidence }
         */
        public AccelerationConfidence getHozAccelCon() {
            return hozAccelCon;
        }

        /**
         * Sets the value of the hozAccelCon property.
         * 
         * @param value allowed object is {@link AccelerationConfidence }
         */
        public void setHozAccelCon(AccelerationConfidence value) {
            this.hozAccelCon = value;
        }

        /**
         * Gets the value of the confidenceSet property.
         * 
         * @return possible object is {@link ConfidenceSet }
         */
        public ConfidenceSet getConfidenceSet() {
            return confidenceSet;
        }

        /**
         * Sets the value of the confidenceSet property.
         * 
         * @param value allowed object is {@link ConfidenceSet }
         */
        public void setConfidenceSet(ConfidenceSet value) {
            this.confidenceSet = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="obDist" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObstacleDistance"/>
     *         &lt;element name="obDirect" type="{http://www.DSRC-Adopted-02-00-36/DSRC}ObstacleDirection"/>
     *         &lt;element name="dateTime" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DDateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "obDist", "obDirect", "dateTime" })
    public static class Object implements Serializable {

        protected int obDist;

        protected int obDirect;

        @XmlElement(required = true)
        protected DDateTime dateTime;

        /**
         * Gets the value of the obDist property.
         */
        public int getObDist() {
            return obDist;
        }

        /**
         * Sets the value of the obDist property.
         */
        public void setObDist(int value) {
            this.obDist = value;
        }

        /**
         * Gets the value of the obDirect property.
         */
        public int getObDirect() {
            return obDirect;
        }

        /**
         * Sets the value of the obDirect property.
         */
        public void setObDirect(int value) {
            this.obDirect = value;
        }

        /**
         * Gets the value of the dateTime property.
         * 
         * @return possible object is {@link DDateTime }
         */
        public DDateTime getDateTime() {
            return dateTime;
        }

        /**
         * Sets the value of the dateTime property.
         * 
         * @param value allowed object is {@link DDateTime }
         */
        public void setDateTime(DDateTime value) {
            this.dateTime = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="angle" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngle"/>
     *         &lt;element name="confidence" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngleConfidence" minOccurs="0"/>
     *         &lt;element name="rate" type="{http://www.DSRC-Adopted-02-00-36/DSRC}SteeringWheelAngleRateOfChange" minOccurs="0"/>
     *         &lt;element name="wheels" type="{http://www.DSRC-Adopted-02-00-36/DSRC}DrivingWheelAngle" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "angle", "confidence", "rate", "wheels" })
    public static class Steering implements Serializable {

        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        protected byte[] angle;

        protected SteeringWheelAngleConfidence confidence;

        protected Byte rate;

        protected Byte wheels;

        /**
         * Gets the value of the angle property.
         * 
         * @return possible object is {@link String }
         */
        public byte[] getAngle() {
            return angle.clone();
        }

        /**
         * Sets the value of the angle property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setAngle(byte[] value) {
            this.angle = ((byte[])value.clone());
        }

        /**
         * Gets the value of the confidence property.
         * 
         * @return possible object is {@link SteeringWheelAngleConfidence }
         */
        public SteeringWheelAngleConfidence getConfidence() {
            return confidence;
        }

        /**
         * Sets the value of the confidence property.
         * 
         * @param value allowed object is {@link SteeringWheelAngleConfidence }
         */
        public void setConfidence(SteeringWheelAngleConfidence value) {
            this.confidence = value;
        }

        /**
         * Gets the value of the rate property.
         * 
         * @return possible object is {@link Byte }
         */
        public Byte getRate() {
            return rate;
        }

        /**
         * Sets the value of the rate property.
         * 
         * @param value allowed object is {@link Byte }
         */
        public void setRate(Byte value) {
            this.rate = value;
        }

        /**
         * Gets the value of the wheels property.
         * 
         * @return possible object is {@link Byte }
         */
        public Byte getWheels() {
            return wheels;
        }

        /**
         * Sets the value of the wheels property.
         * 
         * @param value allowed object is {@link Byte }
         */
        public void setWheels(Byte value) {
            this.wheels = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="height" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleHeight"/>
     *         &lt;element name="bumpers" type="{http://www.DSRC-Adopted-02-00-36/DSRC}BumperHeights"/>
     *         &lt;element name="mass" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleMass"/>
     *         &lt;element name="trailerWeight" type="{http://www.DSRC-Adopted-02-00-36/DSRC}TrailerWeight"/>
     *         &lt;element name="type" type="{http://www.DSRC-Adopted-02-00-36/DSRC}VehicleType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "height", "bumpers", "mass", "trailerWeight", "type" })
    public static class VehicleData implements Serializable {

        protected short height;

        @XmlElement(required = true)
        protected BumperHeights bumpers;

        protected short mass;

        protected int trailerWeight;

        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the height property.
         */
        public short getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         */
        public void setHeight(short value) {
            this.height = value;
        }

        /**
         * Gets the value of the bumpers property.
         * 
         * @return possible object is {@link BumperHeights }
         */
        public BumperHeights getBumpers() {
            return bumpers;
        }

        /**
         * Sets the value of the bumpers property.
         * 
         * @param value allowed object is {@link BumperHeights }
         */
        public void setBumpers(BumperHeights value) {
            this.bumpers = value;
        }

        /**
         * Gets the value of the mass property.
         */
        public short getMass() {
            return mass;
        }

        /**
         * Sets the value of the mass property.
         */
        public void setMass(short value) {
            this.mass = value;
        }

        /**
         * Gets the value of the trailerWeight property.
         */
        public int getTrailerWeight() {
            return trailerWeight;
        }

        /**
         * Sets the value of the trailerWeight property.
         */
        public void setTrailerWeight(int value) {
            this.trailerWeight = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setType(String value) {
            this.type = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isRaining" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipYesNo"/>
     *         &lt;element name="rainRate" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipRate" minOccurs="0"/>
     *         &lt;element name="precipSituation" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssPrecipSituation" minOccurs="0"/>
     *         &lt;element name="solarRadiation" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssSolarRadiation" minOccurs="0"/>
     *         &lt;element name="friction" type="{http://www.DSRC-Adopted-02-00-36/NTCIP}EssMobileFriction" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "isRaining", "rainRate", "precipSituation", "solarRadiation", "friction" })
    public static class WeatherReport implements Serializable {

        @XmlElement(required = true)
        protected EssPrecipYesNo isRaining;

        protected Integer rainRate;

        protected EssPrecipSituation precipSituation;

        protected Integer solarRadiation;

        protected Short friction;

        /**
         * Gets the value of the isRaining property.
         * 
         * @return possible object is {@link EssPrecipYesNo }
         */
        public EssPrecipYesNo getIsRaining() {
            return isRaining;
        }

        /**
         * Sets the value of the isRaining property.
         * 
         * @param value allowed object is {@link EssPrecipYesNo }
         */
        public void setIsRaining(EssPrecipYesNo value) {
            this.isRaining = value;
        }

        /**
         * Gets the value of the rainRate property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getRainRate() {
            return rainRate;
        }

        /**
         * Sets the value of the rainRate property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setRainRate(Integer value) {
            this.rainRate = value;
        }

        /**
         * Gets the value of the precipSituation property.
         * 
         * @return possible object is {@link EssPrecipSituation }
         */
        public EssPrecipSituation getPrecipSituation() {
            return precipSituation;
        }

        /**
         * Sets the value of the precipSituation property.
         * 
         * @param value allowed object is {@link EssPrecipSituation }
         */
        public void setPrecipSituation(EssPrecipSituation value) {
            this.precipSituation = value;
        }

        /**
         * Gets the value of the solarRadiation property.
         * 
         * @return possible object is {@link Integer }
         */
        public Integer getSolarRadiation() {
            return solarRadiation;
        }

        /**
         * Sets the value of the solarRadiation property.
         * 
         * @param value allowed object is {@link Integer }
         */
        public void setSolarRadiation(Integer value) {
            this.solarRadiation = value;
        }

        /**
         * Gets the value of the friction property.
         * 
         * @return possible object is {@link Short }
         */
        public Short getFriction() {
            return friction;
        }

        /**
         * Sets the value of the friction property.
         * 
         * @param value allowed object is {@link Short }
         */
        public void setFriction(Short value) {
            this.friction = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="statusFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusFront"/>
     *         &lt;element name="rateFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate"/>
     *         &lt;element name="statusRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusRear" minOccurs="0"/>
     *         &lt;element name="rateRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "statusFront", "rateFront", "statusRear", "rateRear" })
    public static class Wipers implements Serializable {

        @XmlElement(required = true)
        protected String statusFront;

        protected short rateFront;

        protected String statusRear;

        protected Short rateRear;

        /**
         * Gets the value of the statusFront property.
         * 
         * @return possible object is {@link String }
         */
        public String getStatusFront() {
            return statusFront;
        }

        /**
         * Sets the value of the statusFront property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setStatusFront(String value) {
            this.statusFront = value;
        }

        /**
         * Gets the value of the rateFront property.
         */
        public short getRateFront() {
            return rateFront;
        }

        /**
         * Sets the value of the rateFront property.
         */
        public void setRateFront(short value) {
            this.rateFront = value;
        }

        /**
         * Gets the value of the statusRear property.
         * 
         * @return possible object is {@link String }
         */
        public String getStatusRear() {
            return statusRear;
        }

        /**
         * Sets the value of the statusRear property.
         * 
         * @param value allowed object is {@link String }
         */
        public void setStatusRear(String value) {
            this.statusRear = value;
        }

        /**
         * Gets the value of the rateRear property.
         * 
         * @return possible object is {@link Short }
         */
        public Short getRateRear() {
            return rateRear;
        }

        /**
         * Sets the value of the rateRear property.
         * 
         * @param value allowed object is {@link Short }
         */
        public void setRateRear(Short value) {
            this.rateRear = value;
        }

    }

}
