/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WiperStatus complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WiperStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statusFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusFront"/>
 *         &lt;element name="rateFront" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate"/>
 *         &lt;element name="statusRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperStatusRear" minOccurs="0"/>
 *         &lt;element name="rateRear" type="{http://www.DSRC-Adopted-02-00-36/DSRC}WiperRate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WiperStatus", propOrder = { "statusFront", "rateFront", "statusRear", "rateRear" })
public class WiperStatus implements Serializable {

    @XmlElement(required = true)
    protected String statusFront;

    protected short rateFront;

    protected String statusRear;

    protected Short rateRear;

    /**
     * Gets the value of the statusFront property.
     * 
     * @return possible object is {@link String }
     */
    public String getStatusFront() {
        return statusFront;
    }

    /**
     * Sets the value of the statusFront property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStatusFront(String value) {
        this.statusFront = value;
    }

    /**
     * Gets the value of the rateFront property.
     */
    public short getRateFront() {
        return rateFront;
    }

    /**
     * Sets the value of the rateFront property.
     */
    public void setRateFront(short value) {
        this.rateFront = value;
    }

    /**
     * Gets the value of the statusRear property.
     * 
     * @return possible object is {@link String }
     */
    public String getStatusRear() {
        return statusRear;
    }

    /**
     * Sets the value of the statusRear property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setStatusRear(String value) {
        this.statusRear = value;
    }

    /**
     * Gets the value of the rateRear property.
     * 
     * @return possible object is {@link Short }
     */
    public Short getRateRear() {
        return rateRear;
    }

    /**
     * Sets the value of the rateRear property.
     * 
     * @param value allowed object is {@link Short }
     */
    public void setRateRear(Short value) {
        this.rateRear = value;
    }

}
