/*
 * #%L
 * eTEXAS
 * %%
 * Copyright (C) 2016 Harmonia Holdings Group, LLC
 * %%
 * All rights reserved.
 * -
 * SBIR DATA RIGHTS
 * Harmonia Holdings Group, LLC
 * 2020 Kraft Drive Suite 2400
 * Blacksburg, VA 24060
 * Contract No: DTRT57-16-c-10008
 * Start Date: 01/05/2016
 * End Date: 01/05/2018
 * Expiration of SBIR Data Rights Period: 01/05/2022
 * -
 * The Government's rights to use, modify, reproduce, release, perform,
 * display, or disclose technical data or computer software marked with
 * this legend are restricted during the period shown as provided in
 * paragraph (b)(4) of the Rights in Noncommercial Technical Data and
 * Computer Software-Small Business Innovation Research (SBIR) Program
 * clause contained in the above identified contract. No restrictions
 * apply after the expiration date shown above. Any reproduction of
 * technical data, computer software, or portions thereof marked with
 * this legend must also reproduce the markings.
 * -
 * Contributors:
 * Harmonia Holdings Group LLC: Initial API and implementation.
 * #L%
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 03:16:39 PM EDT 
//

package org.etexascode.j2735;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for YawRateConfidence.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="YawRateConfidence">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="unavailable"/>
 *     &lt;enumeration value="degSec-100-00"/>
 *     &lt;enumeration value="degSec-010-00"/>
 *     &lt;enumeration value="degSec-005-00"/>
 *     &lt;enumeration value="degSec-001-00"/>
 *     &lt;enumeration value="degSec-000-10"/>
 *     &lt;enumeration value="degSec-000-05"/>
 *     &lt;enumeration value="degSec-000-01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "YawRateConfidence")
@XmlEnum
public enum YawRateConfidence {

    @XmlEnumValue("unavailable")
    UNAVAILABLE("unavailable"),
    @XmlEnumValue("degSec-100-00")
    DEG_SEC_100_00("degSec-100-00"),
    @XmlEnumValue("degSec-010-00")
    DEG_SEC_010_00("degSec-010-00"),
    @XmlEnumValue("degSec-005-00")
    DEG_SEC_005_00("degSec-005-00"),
    @XmlEnumValue("degSec-001-00")
    DEG_SEC_001_00("degSec-001-00"),
    @XmlEnumValue("degSec-000-10")
    DEG_SEC_000_10("degSec-000-10"),
    @XmlEnumValue("degSec-000-05")
    DEG_SEC_000_05("degSec-000-05"),
    @XmlEnumValue("degSec-000-01")
    DEG_SEC_000_01("degSec-000-01");

    private final String value;

    YawRateConfidence(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static YawRateConfidence fromValue(String v) {
        for (YawRateConfidence c : YawRateConfidence.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
